### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by ptahchiev** [oracle/docker-images#451] opened 2017-07-06 14:14 UTC
Hello I downloaded the zip and installed it in the 12.2.0.1 folder:

````
petar@petar-XPS-15-9550:~/workspace/docker-images/OracleDatabase/dockerfiles/12.2.0.1$ ll
total 3372844
drwxrwxr-x 2 petar petar       4096 Jul  6 15:45 ./
drwxrwxr-x 5 petar petar       4096 Jul  6 16:57 ../
-rwxrwxr-x 1 petar petar       1259 Jul  6 14:56 checkDBStatus.sh*
-rwxrwxr-x 1 petar petar        839 Jul  6 14:56 checkSpace.sh*
-rw-rw-r-- 1 petar petar         63 Jul  6 14:56 Checksum.ee
-rw-rw-r-- 1 petar petar         63 Jul  6 14:56 Checksum.se2
-rwxrwxr-x 1 petar petar       2898 Jul  6 14:56 createDB.sh*
-rw-rw-r-- 1 petar petar       9406 Jul  6 14:56 dbca.rsp.tmpl
-rw-rw-r-- 1 petar petar       7002 Jul  6 14:56 db_inst.rsp
-rw-rw-r-- 1 petar petar       2625 Jul  6 14:56 Dockerfile.ee
-rw-rw-r-- 1 petar petar       2627 Jul  6 14:56 Dockerfile.se2
-rwxrwxr-x 1 petar petar       2057 Jul  6 14:56 installDBBinaries.sh*
-rwxrwxr-x 1 petar petar       1065 Jul  6 14:56 installPerl.sh*
-rw-rw-r-- 1 petar petar 3453696911 Jul  6 15:43 linuxx64_12201_database.zip
-rwxrwxr-x 1 petar petar       5332 Jul  6 14:56 runOracle.sh*
-rwxrwxr-x 1 petar petar        769 Jul  6 14:56 setPassword.sh*
-rwxrwxr-x 1 petar petar        746 Jul  6 14:56 setupLinuxEnv.sh*
-rwxrwxr-x 1 petar petar        689 Jul  6 14:56 startDB.sh*

````
Then I run the build script and it's telling me no such file:
````
petar@petar-XPS-15-9550:~/workspace/docker-images/OracleDatabase/dockerfiles$ ./buildDockerImage.sh -v 12.2.0.1 -e
Checking if required packages are present and valid...
md5sum: 'linuxx64_12201_database.zip'$'\r': No such file or directory
: FAILED open or readse.zip
md5sum: WARNING: 1 listed file could not be read
MD5 for required packages to build this image did not match!
Make sure to download missing files in folder 12.2.0.1.
````
I use ubuntu linux 16.04:
````
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
````

**Comment by ptahchiev** [comment] 2017-07-06 14:17
Ok my bad: `-i` will ignore the checksum check.

**Comment by Djelibeybi** [comment] 2017-07-06 15:37
@gvenzl is it worth testing the build script on Ubuntu? I'm wondering if there is a command/path problem that prevents the md5sum from being properly validated.

**Comment by gvenzl** [comment] 2017-07-06 16:08
Sure would be worth if you can give me an Ubuntu environment to test against. :)
The output sure does look strange: `md5sum: 'linuxx64_12201_database.zip'$'\r': No such file or directory`. Almost as if the line feed is included in the file name or something.

**Comment by Djelibeybi** [comment] 2017-07-06 16:12
I wonder if the EOL characters in the `Checksum.ee` are munged somehow?

**Comment by gvenzl** [comment] 2017-07-06 16:16
On my local environment it certainly is Unix LF.

**Comment by gvenzl** [comment] 2017-07-14 06:20
Closing this for now as the issue is solved and cannot be reproduced.

**Closed by gvenzl** 2017-07-14 06:20 UTC
Labels: database, help wanted
