### ISSUE TITLE
OracleDatabase: Error when trying to compile procedure in native mode

### ISSUE THREAD

**Issue by doberkofler** [oracle/docker-images#1302] opened 2019-05-29 18:27 UTC
When trying to compile procedural code in native mode in a docker container the compilation reports an error as follows: `ORA-00600: internal error code, arguments: [pesldl03_MMap: errno 1 errmsg Operation not permitted], [], [], [], [], [], [], [], [], [], [], []`.
(This might be related to the oracle bug 18076018)

I have build a docker single instance image based on the 18.3 se2 scripts.

Example in sqlplus:

```
alter session set plsql_code_type='NATIVE';

create or replace procedure test as
begin
   null;
end;
/
```

**Comment by zeroastro** [comment] 2019-07-03 09:11
I've been facing the same issue, and I found that the problem is with with the mount options of `/dev/shm`. I solved the issue using `rw` and `exec` mount options for it. I've also specified a size, but I don't think that's necessary for the fix.

So, you can run 
```
docker run -it -v /dev/shm --tmpfs /dev/shm:rw,exec,size=<yoursize>
```

or, in docker-compose (I was using ver 2.1), you can do something like
```
  your-service:
    ...
    tmpfs:
      - /dev/shm:exec,rw,size=<yoursize>
```

Hope this helps

**Comment by gvenzl** [comment] 2019-08-09 03:41
Indeed, it's to do how Docker handles `/dev/shm` and that there is no execution right by default, hence the permission denied.

@doberkofler, have you verified the solution?

**Comment by doberkofler** [comment] 2019-08-09 04:37
@gvenzl Yes, I'm manually altering the mount options but in my opinion this should be part of the Docker image creation itself or it should be clearly documented that native compilation is not (yet) supported by this docker image.

**Comment by gvenzl** [comment] 2019-08-09 16:21
Hi @doberkofler, unfortunately this cannot be part of the Docker image creation as this is a Docker runtime configuration, i.e. it has to be set per container and therefore can only be done during `docker run`. Not our limitations, but that's how Docker does it.

However, this error is a great addition to the FAQ which I have PRed in now in #1351 
Thanks a lot for that! :)

**Comment by gvenzl** [comment] 2019-08-11 18:31
Closing as PR has been merged.

**Closed by gvenzl** 2019-08-11 18:31 UTC
Labels: database, help wanted

**Comment by doberkofler** [comment] 2019-08-11 19:38
Hi @gvenzl. I'm not sure I understand why this setting cannot be set in der Linux image itself that is used by the Oracle installation?

**Comment by gvenzl** [comment] 2019-08-13 17:45
Because this setting can only be passed on by [`docker run`](https://docs.docker.com/engine/reference/run/) but not in [`docker build`](https://docs.docker.com/engine/reference/commandline/build/). And even if you could pass it on in `docker build`, the setting is overwritten to the default by `docker run` unless specified differently.
