### ISSUE TITLE
Latest 5.0 images don't have java installed

### ISSUE THREAD

**Issue by j-bro** [oracle/docker-images#929] opened 2018-07-10 12:49 UTC
The automated image build wasn't able to resolve the openjdk 1.8 dependency:

**No package java-1.8.0-openjdk-1.8.0.151-5.b12.el7_4 available.**

Therefore the image does not contain a java installation and running commands such as `asadmin` fail with **exec: java: not found**.

From the Docker build log for 5.0 and 5.0-web:

```
Step 4/8 : RUN yum -y install unzip java-1.8.0-openjdk-1.8.0.151-5.b12.el7_4 && curl -O $GLASSFISH_URL && echo "$MD5 *$GLASSFISH_PKG" | md5sum -c - && unzip -o $GLASSFISH_PKG && rm -f $GLASSFISH_PKG && yum -y remove unzip && rm -rf /var/cache/yum ---> 
Running in 3232e30ccb00 
Loaded plugins: ovl 
No package java-1.8.0-openjdk-1.8.0.151-5.b12.el7_4 available.
Resolving Dependencies --> 
Running transaction check ---> 
Package unzip.x86_64 0:6.0-19.el7 will be installed --> 
Finished Dependency Resolution Dependencies Resolved
================================================================================
Package Arch Version Repository Size
================================================================================
Installing: unzip x86_64 6.0-19.el7 ol7_latest 169 k Transaction Summary
================================================================================
Install 1 Package
```

See [https://hub.docker.com/r/oracle/glassfish/builds/bwgvjqda34hjeqhw86l6sd9/](https://hub.docker.com/r/oracle/glassfish/builds/bwgvjqda34hjeqhw86l6sd9/) for the full log.

**Comment by arindam-bandyopadhyay** [comment] 2018-07-17 14:36
We used java-1.8.0-openjdk-1.8.0.151-5.b12.el7_4 instead of java-1.8.0-openjdk in order to fix https://github.com/oracle/docker-images/issues/727 (upstream issue - https://github.com/javaee/glassfish/issues/22407). Though the issue is fixed in upstream repository, it's not backported to 5.0 (and there is no plan for backporting and re-release GlassFish 5.0). So GlassFish 5.0 can work with 1.8.0.151<=GlassFish_Java_Version<= 1.8.0.141
Moreover,  java-1.8.0-openjdk-1.8.0.151 is removed from ol7_latest repo (https://blogs.oracle.com/linux/upcoming-change-to-oracle-linux-package-channels)
So it's really difficult to fix this issue.

**Comment by referup-cfiguera** [comment] 2018-07-27 07:22
"So it's really difficult to fix this issue" is the best comment I've ever seen. I'll add "So it's really difficult to use Oracle products."

**Closed** 2018-07-27 22:38 UTC
Labels: bug, help wanted
