### ISSUE TITLE
-e ORACLE_PWD=password doesn't work

### ISSUE THREAD

**Issue by e1999b** [oracle/docker-images#2567] opened 2023-02-20 14:04 UTC
when running the container i tried to set enviorment variable -e ORACLE_PWD=admin and when i try to log in using SQL developer tool it says invalid username/password

**Comment by oraclesean** [comment] 2023-02-20 15:08
There could be any number of reasons for this:

- The container wasn't mapped to a port
- The SQL Developer connection is using an incorrect port/hostname/SID
- SQL Developer is connecting to a user other than SYS or SYSTEM
- The SQL Developer connection uses SYS but doesn't connect with the SYSDBA option
- The password isn't really `admin` and uses a reserved character
- etc.

Try:
`docker exec -it <your container name> bash`
Then:
`sqlplus system/admin@<service name>`
...where `<service name>` is the SID or service name of the container database.

If that works, the `SYSTEM` user password was set according to the `ORACLE_PWD` option given during container startup. If not, please share more information about the problem, including the database version; information on how the image was created (was it pulled from a registry or built from this repo, noting any modifications made); the full `docker run` command, the container's `docker logs` output showing database creation, the error message from SQL Developer with the connection metadata being used, and results from the SQL*Plus test above.

**Comment by aditya059** [comment] 2023-03-07 05:54
@e1999b We ran the container with ORACLE_PWD=admin and were able to connect to the database successfully using sqlplus. Since we are not able to reproduce the issue, we are closing it. Please reopen with more information if the issue is seen.

**Closed** 2023-03-07 06:03 UTC
Labels: database
