### ISSUE TITLE
Exposed Ports Are Not Accessible For Oracle 18c XE

### ISSUE THREAD

**Issue by arnab-das** [oracle/docker-images#1545] opened 2020-03-09 17:28 UTC
I've the following configuration

Ubuntu 18.04
Docker 19.03.6

Built the docker image for Oracle 18c XE following the [instructions](https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance) and ran the image with the following command

`docker run -d --name oracle18cxe -p 28080:8080 -p 25500:5500 -p 21521:1521 -e ORACLE_PWD=sAdnew123 oracle/database:18.4.0-xe`

Now, whenever I do `curl -k https://localhost:25500/em` on the host, I get `Connection reset by peer`. What am I doing wrong?

**Comment by gvenzl** [comment] 2020-03-13 21:17
Tried to rerun that and get a similar issue:

```
[oracle@ol7 ~]$ curl -k https://localhost:25500/em
curl: (35) Encountered end of file
```

I could work around by resetting the port:

```
[oracle@ol7 ~]$ docker exec -ti oracle18cxe su -p oracle -c "sqlplus / as sysdba"

SQL*Plus: Release 18.0.0.0.0 - Production on Fri Mar 13 21:14:52 2020
Version 18.4.0.0.0

Copyright (c) 1982, 2018, Oracle.  All rights reserved.


Connected to:
Oracle Database 18c Express Edition Release 18.0.0.0.0 - Production
Version 18.4.0.0.0

SQL> exec DBMS_XDB_CONFIG.SETHTTPSPORT(0);

PL/SQL procedure successfully completed.

SQL> exec DBMS_XDB_CONFIG.SETHTTPSPORT(5500);

PL/SQL procedure successfully completed.

SQL> exit
Disconnected from Oracle Database 18c Express Edition Release 18.0.0.0.0 - Production
Version 18.4.0.0.0
[oracle@ol7 ~]$ curl -k https://localhost:25500/em
HTTP/1.1 200 OK
MS-Author-Via: DAV
DAV: 1,2,<http://www.oracle.com/xdb/webdav/props>
Server: Oracle XML DB/Oracle Database
Location: /em/login
Transfer-Encoding: chunked

0

^C
[oracle@ol7 ~]$
```

Can you try that?

**Comment by alesana-san** [comment] 2020-03-15 19:34
Hi again! Faced exactly the same issue. Tried @gvenzl solution and it worked for me (except I checked it right from my host machine and browser opened EM page).

**Comment by ivgg-me** [comment] 2020-03-16 06:37
Hi! Same issue by me on Windows 10 with the newest Docker Desktop Community 2.2.0.4 (43472). Workaround from @gvenzl works.

**Comment by gvenzl** [comment] 2020-03-19 16:08
Closing this issue as a workaround is available and the issue is related to OEM Express in XE, rather than the Docker build files.

**Closed by gvenzl** 2020-03-19 16:08 UTC
Labels: database, invalid, question
