### ISSUE TITLE
Could not build java8 image from Windows 10 Host

### ISSUE THREAD

**Issue by pcouas** [oracle/docker-images#181] opened 2016-10-12 04:22 UTC
Hi Bruno

I have tried to build then to running DockerFile issue your DockerFile from my Windows10Pro Host
I could build it
But when i run, i have only # caracter ?
I could not enter any caracter ?

Regards
Philippe
`
# LICENSE CDDL 1.0 + GPL 2.0
#
# Copyright (c) 2015 Oracle and/or its affiliates. All rights reserved.
#
FROM oraclelinux:latest

MAINTAINER Bruno Borges <bruno.borges@oracle.com>

ENV JAVA_PKG=server-jre-8u102-linux-x64.tar.gz \
    JAVA_HOME=/usr/java/default \
    PATH=$PATH:/usr/java/default/bin

ADD $JAVA_PKG /usr/java/

RUN mv $(ls -1 -d /usr/java/*) $JAVA_HOME 
`

**Comment by brunoborges** [comment] 2016-10-12 15:54
I am sorry I won't be able to help you. I don't have Windows.

**Comment by gvenzl** [comment] 2016-10-12 17:29
The host shouldn't matter so much if the problem is somewhere while building the Docker container or inside the container. But I'm not clear that the outcome/problem is. Here is what I get on Mac OS X:

    gvenzl-mac:java-8 gvenzl$  docker build -t oracle/jdk:8 .
    Sending build context to Docker daemon 59.88 MB
    Step 1 : FROM oraclelinux:latest
     ---> 3d62999fc909
    Step 2 : MAINTAINER Bruno Borges <bruno.borges@oracle.com>
     ---> Running in acb568b577fd
     ---> 2a9b16688d42
    Removing intermediate container acb568b577fd
    Step 3 : ENV JAVA_PKG server-jre-8u*-linux-x64.tar.gz JAVA_HOME /usr/java/default
     ---> Running in cd2f75da62ac
     ---> 19bb4a4b7786
    Removing intermediate container cd2f75da62ac
    Step 4 : ADD $JAVA_PKG /usr/java/
     ---> 04543422c376
    Removing intermediate container 841fb66d710e
    Step 5 : RUN export JAVA_DIR=$(ls -1 -d /usr/java/*) &&     ln -s $JAVA_DIR /usr/java/latest &&     ln -s $JAVA_DIR /usr/java/default &&     alternatives --install /usr/bin/java java $JAVA_DIR/bin/java 20000 &&     alternatives --install /usr/bin/javac javac $JAVA_DIR/bin/javac 20000 &&     alternatives --install /usr/bin/jar jar $JAVA_DIR/bin/jar 20000
     ---> Running in 4f98344f95ea
     ---> 2fe3663bc3a7
    Removing intermediate container 4f98344f95ea
    Successfully built 2fe3663bc3a7
    gvenzl-mac:java-8 gvenzl$ docker run -ti oracle/jdk:8 /bin/bash
    [root@0bbb96267fda /]# java -version
    java version "1.8.0_101"
    Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
    [root@0bbb96267fda /]# exit
    exit
    gvenzl-mac:java-8 gvenzl$

**Comment by brunoborges** [comment] 2016-10-12 17:50
@gvenzl, my point is that it is not clear whether @pcouas is building this container on Docker Toolbox for Windows (which runs a small Linux VM), or if is trying to build directly on Docker *for* Windows.

@pcouas, please provide more details on what Docker stack you have installed in your Windows environment, and what steps you took trying to build the image.

**Comment by pcouas** [comment] 2016-10-13 05:06
Hi

I have intalled DockerToolbox-1.12.0.exe in my Windows10PRO from url https://www.docker.com/products/docker-toolbox

**Comment by brunoborges** [comment] 2016-10-13 16:42
Please provide all steps you took to attempt the build.

**Comment by brunoborges** [comment] 2016-10-26 19:04
@pcouas, let me know if you still having problem. Closing for now.

**Closed by brunoborges** 2016-10-26 19:04 UTC
Labels: help wanted, java

**Comment by pcouas** [comment] 2016-10-27 15:35
Yes I HAVE Still problem i see this problem next week

 

 

 

 

 

> Message du 26/10/16 21:05
> De : "Bruno Borges" 
> A : "oracle/docker-images" 
> Copie à : "pcouas" 
, "Mention" 
> Objet : Re: [oracle/docker-images] Could not build java8 image from Windows 10 Host (#181)
> 
>
> @pcouas, let me know if you still having problem. Closing for now.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/oracle/docker-images","title":"oracle/docker-images","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/oracle/docker-images"}},"updates":{"snippets":[{"icon":"PERSON","message":"@brunoborges in #181: @pcouas, let me know if you still having problem. Closing for now."}],"action":{"name":"View Issue","url":"https://github.com/oracle/docker-images/issues/181#issuecomment-256446279"}}}

**Comment by brunoborges** [comment] 2016-10-27 18:29
I'll reopen this bug when you provide the detailed procedure you took to attempt building this image.
