### ISSUE TITLE
min docker version check fails on docker 24.0.5

### ISSUE THREAD

**Issue by robert-s-lee** [oracle/docker-images#2688] opened 2023-08-23 12:48 UTC
upgraded to new docker version on a mac
```
docker --version
Docker version 24.0.5, build ced0996
```

build fails on docker version check
```./buildContainerImage.sh -f -v 23.2.0   # will build oracle/database:21.3.0-xe
WARNING: daemon is not using the default seccomp profile
Checking Docker version.
Docker version is below the minimum required version 17.09
Please upgrade your Docker installation to proceed.
```

the issues comes from 

https://github.com/oracle/docker-images/blob/446229a885b9180aeac12c333bece3ad663a556d/OracleDatabase/SingleInstance/dockerfiles/buildContainerImage.sh#L93C1-L94C1
which reports `24.0` and not `24.00`

```
DOCKER_VERSION=$("${CONTAINER_RUNTIME}" version --format '{{.Server.Version }}'|| exit 0)
pple:~ rslee$ echo $DOCKER_VERSION
24.0
```

**Comment by aditya059** [comment] 2023-08-30 08:29
Hi @robert-s-lee 

I tried the same on my mac. I am not getting this error. 

mac ~ % docker --version
Docker version 24.0.5, build ced0996
mac ~ % 
mac ~ % 
mac ~ % DOCKER_VERSION=$(docker version --format '{{.Server.Version }}'|| exit 0)
mac ~ % echo $DOCKER_VERSION
24.0.5

**Comment by aditya059** [comment] 2023-08-31 14:18
Closing this issue as it is not reproducible at our end

**Closed by aditya059** 2023-08-31 14:18 UTC
Labels: database

**Comment by aditya059** [comment] 2023-09-01 06:49
@robert-s-lee 
Yes, its strange. I guess it is happening only on your machine because we haven't had anyone else filing this issue.
