### ISSUE TITLE
Error when restarting a configured database on Oracle Database 18.4.0-xe

### ISSUE THREAD

**Issue by rolaca11** [oracle/docker-images#1230] opened 2019-04-15 18:37 UTC
I built the docker image for the 18.4.0-xe version of Oracle Database, I started it up and it configured a working database. When I tried to stop and restart the container, I got this error message:

> [FATAL] [DBT-06607] The data file (/opt/oracle/oradata/XE/system01.dbf) already exists on the file system.
   CAUSE: This configuration    is going to create the data file location (/opt/oracle/oradata/XE/system01.dbf). But it is detected that there is an existing database using this data file location or the data files from a previous configuration may be left behind.
   ACTION: Clean up the existing data files, or provide a different db_unique_name.

After a lot of trial and error/re-reading the documentation, I found out the mistake. I was to blame for this anomaly, but I feel like there could be some improvement made to the database configuration script as well.

The problem was that I was reading the documentation on how to run a container based on the Standard Edition, which means that I set the ORACLE_PWD and ORACLE_SID environment variables as well, which confused the configuration script, creating folders/files with names based on those variables, when it should just ignore them. Since these folders and files are named with the above mentioned variables in mind, but the start script is not, the script will find that there is no database configured, but the configuration script will find that there actually is a database configured, meaning it will fail with error.

Maybe more info can be found [here](https://stackoverflow.com/questions/55435327/docker-oracle-database-18-4-0-xe-wants-to-configure-a-new-database-on-startup/55695116#55695116)

**Comment by jesusmorenodiaz** [comment] 2019-05-15 02:36
You installed 18c XE with success in which OS?

**Comment by ckristo** [comment] 2021-11-04 09:39
Have experienced this issue today as well - Docker image of Oracle XE 18c build with [buildContainerImage.sh](https://github.com/oracle/docker-images/blob/main/OracleDatabase/SingleInstance/dockerfiles/buildContainerImage.sh). Rebuilding the Docker container and using an existing volume containing an already configured Oracle XE database gives me the same error.

**Comment by abhisbyk** [comment] 2022-04-27 07:06
@ckristo Can you try Oracle Database 21.3.0 XE image, and see if the problem persists ?
While running this image, please specify `-e ORACLE_SID=XE` in the `docker run` command.

**Comment by abhisbyk** [comment] 2022-04-27 07:12
@rolaca11 with XE version 21.3.0 onwards, we have common scripts to configure the enterprise/express edition. The only differentiating point is the `ORACLE_SID` which should be equal to `XE`. If one choose not to specify `ORACLE_SID` for the express edition, it will automatically take `ORACLE_SID` as `XE` but if wrong value is given to `ORACLE_SID` the database setup is bound to fail.

**Comment by abhisbyk** [comment] 2022-05-24 10:28
Unable to reproduce the same with Oracle 21.3.0 XE container image. Closing this issue for now. Please reopen if the issue exist in 21.3.0 XE container image.

**Closed by abhisbyk** 2022-05-24 10:28 UTC
Labels: enhancement, database, more-info-required
