### ISSUE TITLE
ORACLE BI docker image creation fail

### ISSUE THREAD

**Issue by TimHespel** [oracle/docker-images#1110] opened 2019-01-09 11:03 UTC
Hi 

it seems that there is a problem with the dependencies with the shell 
buildDockerImage.sh

Step 1/14 : FROM oracle/fmw-infrastructure:12.2.1.2
pull access denied for oracle/fmw-infrastructure, repository does not exist or may require 'docker login'

I manually checked and have not been able to find a github project at oracle named oracle/fmw-infrastructure. 

Could you please give me a clue ?

Thanks

**Comment by TimHespel** [comment] 2019-01-09 14:36
Ok I have fixed it. In the OracleBI/dockerfiles/12.2.1.2/Dockerfile the pull base image URL is incorrect : 
FROM store/oracle/fmw-infrastructure:12.2.1.2 instead of FROM oracle/fmw-infrastructure:12.2.1.2

Will probably try a merge request to fix it soon

**Comment by Djelibeybi** [comment] 2019-01-09 19:47
It's not incorrect. Each `Dockerfile` in this repo assumes you've manually built the dependent image(s) first. If you want to build the BI image, you need to build the FMW image first (or manually modify it like you did to point to the store image).

**Comment by TimHespel** [comment] 2019-01-10 07:49
I see.
Maybe we could just add an argument to define how to manage the fmw image ?
Let me know if you think it is a good idea and/or if you want me to do it



Timothée
+33762338917<tel:+33762338917>
Le Avi Miller <notifications@github.com>, 9 janv. 2019 22:01 a écrit :

It's not incorrect. Each Dockerfile in this repo assumes you've manually built the dependent image(s) first. If you want to build the BI image, you need to build the FMW image first (or manually modify it like you did to point to the store image).

**Comment by Djelibeybi** [comment] 2019-04-10 20:49
Closing as this is not a bug.

**Closed by Djelibeybi** 2019-04-10 20:49 UTC
Labels: businessintelligence
