### ISSUE TITLE
Running Docker Oracle Database in Kubernetes fails

### ISSUE THREAD

**Issue by eldada** [oracle/docker-images#328] opened 2017-03-21 06:26 UTC
I built the Docker image from version [12.2.0.1](https://github.com/oracle/docker-images/tree/master/OracleDatabase/dockerfiles/12.2.0.1).
The build was fine. Ran it on my Mac successfully. My application was able to connect to it without a problem.
The command I used to run on my mac was
```
docker run -d --name oracle -p 1521:1521 -p 5500:5500 -e ORACLE_SID=ORADB -v ~/.oracle:/opt/oracle/oradata oracle/database:12.2.0.1-se2
```

I then moved to running it on a Kubernetes cluster I have in GCP.
My yaml files looks like this
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oracle.eldadtestsabcoracle
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: oracle.eldadtestsabcoracle
    spec:
      containers:
      - name: db-eldadtestsabcoracle
        image: my-docker-registry/oracle-database:12.2.0.1-se2
        env:
        - name: ORACLE_SID
          value: ORADB
        ports:
        - containerPort: 1521
      imagePullSecrets:
      - name: docker-reg-secret
---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  ports:
  - port: 1521
    protocol: TCP
  selector:
    app: oracle.eldadtestsabcoracle
```

When I deploy it, it comes up with many errors and crashes
```
ORACLE AUTO GENERATED PASSWORD FOR SYS, SYSTEM AND PDBAMIN: 6CF/CNMYz2s=1

LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 21-MAR-2017 06:15:52

Copyright (c) 1991, 2016, Oracle.  All rights reserved.

Starting /opt/oracle/product/12.2.0.1/dbhome_1/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 12.2.0.1.0 - Production
System parameter file is /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/oracle/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 12.2.0.1.0 - Production
Start Date                21-MAR-2017 06:15:52
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/oracle/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
[FATAL] [DBT-06103] The port (5,500) is already in use.
   ACTION: Specify a free port.
[WARNING] [DBT-10102] The listener configuration is not selected for the database. EM DB Express URL will not be accessible.
   CAUSE: The database should be registered with a listener in order to access the EM DB Express URL.
   ACTION: Select a listener to be registered or created with the database.
cat: /opt/oracle/cfgtoollogs/dbca/ORADB/ORADB.log: No such file or directory
cat: /opt/oracle/cfgtoollogs/dbca/ORADB.log: No such file or directory

SQL*Plus: Release 12.2.0.1.0 Production on Tue Mar 21 06:16:00 2017

Copyright (c) 1982, 2016, Oracle.  All rights reserved.

Connected to an idle instance.

SQL>    ALTER SYSTEM SET control_files='/opt/oracle/oradata/ORADB/control01.ctl' scope=spfile
*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0


SQL>    ALTER PLUGGABLE DATABASE ORCLPDB1 SAVE STATE
*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0


SQL> Disconnected
mv: cannot stat '/opt/oracle/product/12.2.0.1/dbhome_1/dbs/spfileORADB.ora': No such file or directory
mv: cannot stat '/opt/oracle/product/12.2.0.1/dbhome_1/dbs/orapwORADB': No such file or directory
#########################
DATABASE IS READY TO USE!
#########################
tail: cannot open '/opt/oracle/diag/rdbms/*/*/trace/alert*.log' for reading: No such file or directory
tail: no files remaining

```

Any ideas?

**Comment by gvenzl** [comment] 2017-03-21 09:18
Hi @eldada, looks like the the culprit is `[FATAL] [DBT-06103] The port (5,500) is already in use.` I notice that you don't have port 5500 in your yaml file. Could that be the issue?

**Comment by eldada** [comment] 2017-03-21 10:44
I added the port to the yaml, and the error is still there
```
ORACLE AUTO GENERATED PASSWORD FOR SYS, SYSTEM AND PDBAMIN: g2Yq0q7AyDA=1

LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 21-MAR-2017 10:33:49

Copyright (c) 1991, 2016, Oracle.  All rights reserved.

Starting /opt/oracle/product/12.2.0.1/dbhome_1/bin/tnslsnr: please wait...

TNSLSNR for Linux: Version 12.2.0.1.0 - Production
System parameter file is /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
Log messages written to /opt/oracle/diag/tnslsnr/oracle/listener/alert/log.xml
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=IPC)(KEY=EXTPROC1)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 12.2.0.1.0 - Production
Start Date                21-MAR-2017 10:33:49
Uptime                    0 days 0 hr. 0 min. 0 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
Listener Log File         /opt/oracle/diag/tnslsnr/oracle/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
The listener supports no services
The command completed successfully
[FATAL] [DBT-06103] The port (5,500) is already in use.
   ACTION: Specify a free port.
[WARNING] [DBT-10102] The listener configuration is not selected for the database. EM DB Express URL will not be accessible.
   CAUSE: The database should be registered with a listener in order to access the EM DB Express URL.
   ACTION: Select a listener to be registered or created with the database.
cat: /opt/oracle/cfgtoollogs/dbca/ORADB/ORADB.log: No such file or directory
cat: /opt/oracle/cfgtoollogs/dbca/ORADB.log: No such file or directory

SQL*Plus: Release 12.2.0.1.0 Production on Tue Mar 21 10:33:58 2017

Copyright (c) 1982, 2016, Oracle.  All rights reserved.

Connected to an idle instance.

SQL>    ALTER SYSTEM SET control_files='/opt/oracle/oradata/ORADB/control01.ctl' scope=spfile
*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0


SQL>    ALTER PLUGGABLE DATABASE ORCLPDB1 SAVE STATE
*
ERROR at line 1:
ORA-01034: ORACLE not available
Process ID: 0
Session ID: 0 Serial number: 0


SQL> Disconnected
mv: cannot stat '/opt/oracle/product/12.2.0.1/dbhome_1/dbs/spfileORADB.ora': No such file or directory
mv: cannot stat '/opt/oracle/product/12.2.0.1/dbhome_1/dbs/orapwORADB': No such file or directory
#########################
DATABASE IS READY TO USE!
#########################
tail: cannot open '/opt/oracle/diag/rdbms/*/*/trace/alert*.log' for reading: No such file or directory
tail: no files remaining
```

Anyway to disable the OEM?
Why would a busy port be related to file system errors?

BTW - with all these errors, you can't output
```
#########################
DATABASE IS READY TO USE!
#########################
```
It's misleading. This is IMHO a bug...

**Comment by eldada** [comment] 2017-03-26 18:59
@gvenzl - any update on this?

**Comment by gvenzl** [comment] 2017-03-30 17:12
Hi @eldada,

To answer your questions in order:

Yes, OEM can be disabled by removing following lines in `dbca.rsp.tmpl`:   
`emConfiguration=DBEXPRESS`  
`emExpressPort=5500`  
Alternatively you can also just change the port if you still want to have OEM Express.

Because of that error, the database is not installed. The install script falls through with the next commands to follow which is why you see SQL statement and file system commands failing.

Yes, you are right. The line that the database is ready to be used is indeed misleading. We will add better checks whether the install has been successful and whether you can log on to the database.

However, all of that still does not explain the root cause why port 5500 is already being using inside your docker container. With nothing else running, the port should be free. You may just find out when disabling OEM that there are other issues which prevent you from running the container.

**Comment by eldada** [comment] 2017-04-01 17:42
I will try and test your proposal this week.
I wonder what is port 5500 busy on. It's in a Kubernetes cluster in GCP...

**Comment by gvenzl** [comment] 2017-04-01 21:16
Can it be that it collides with another node on the forwarded port?

**Comment by eldada** [comment] 2017-04-06 17:37
@gvenzl - I followed your suggestions and tried both options.
The good new: Removing OEM as you suggested worked and the container came up properly. No errors.
The bad news: Changing the port did not help. I still got the conflict error, which breaks the whole DB as described before.
```
...
[FATAL] [DBT-06103] The port (5,505) is already in use.
...
```
I would guess it's conflicting with itself. It probably already has an instance running...
I'll leave it up to you to close or leave this open.

**Comment by gvenzl** [comment] 2017-04-13 17:43
Thanks a lot for the feedback, @eldada! Unfortunately I cannot reproduce this issue. On a fresh container there is no OEM Express running yet so I don't see how it can conflict with itself. Given that no other user has reported similar issues and your issue has been solved I will close this for now.

**Closed by gvenzl** 2017-04-13 17:43 UTC
Labels: database
