### ISSUE TITLE
Rights to setup files in XE 18.4.0

### ISSUE THREAD

**Issue by mkmayer** [oracle/docker-images#1930] opened 2021-05-04 12:00 UTC
Hello, 
tried to run XE 18.4.0 in docker, but there is problem with rights to setup (sh) files. They are copied, but chown not set. User oracle doesnt have access to 3 shell scripts.

In file
/docker-images/OracleDatabase/SingleInstance/dockerfiles/18.4.0/Dockerfile.xe
... there is missing line with chown before chmod ug+x $ORACLE_BASE/*.sh:
chown -R oracle:oinstall $ORACLE_BASE/*.sh && \

Then setup is working well.

**Comment by abhisbyk** [comment] 2022-03-11 15:31
@mkmayer Oracle DB XE 21.3.0 is available now. Can you pls try with it and check whether the same problem exists there ?

**Comment by abhisbyk** [comment] 2022-04-27 07:25
@mkmayer any update on this issue ?

**Comment by abhisbyk** [comment] 2022-05-24 11:07
Unable to reproduce this in Oracle Database 21.3.0 XE image. Closing this issue for now.

Please reopen in case of any problem. Thanks.

**Closed by abhisbyk** 2022-05-24 11:07 UTC
Labels: enhancement, database, more-info-required
