### ISSUE TITLE
OracleDatabase 19.3.0 ERROR [stage-2 2/3]  11/17  orainstRoot.sh: No such file or directory given enough storage 

### ISSUE THREAD

**Issue by tsvirs** [oracle/docker-images#1872] opened 2021-03-13 07:48 UTC
Hello, when execute ` sudo ./buildContainerImage.sh -v 19.3.0 -e`, during the execution of the creation of the image...
` > [stage-2 2/3] RUN /opt/oracle/oraInventory/orainstRoot.sh &&     /opt/oracle/product/19c/dbhome_1/root.sh:                                                                                                                         
#13 0.925 /bin/sh: /opt/oracle/oraInventory/orainstRoot.sh: No such file or directory    
`

I'm not sure if it might due to insufficient space because it seems the storage is more than enough.

`/ # df -B 1G /
Filesystem           1G-blocks      Used Available Use% Mounted on
overlay                    126        70        49  59% /`

**Comment by yunus-qureshi** [comment] 2021-03-24 07:00
Please take a look at this @Mahi0911

**Comment by Mahi0911** [comment] 2021-03-25 06:00
Your build has not created all files with necessary permissions . Run the build again .
Also , can you  run " df -B 1G / " inside the container and post the output, please?

**Comment by tsvirs** [comment] 2021-03-27 03:50
![image](https://user-images.githubusercontent.com/19851229/112709253-abc55c00-8ef2-11eb-9256-693b63a27b85.png)

**Comment by tsvirs** [comment] 2021-03-27 04:01
/ # df -B 1G / Filesystem 1G-blocks Used Available Use% Mounted on overlay 126 70 49 59% /

**Comment by tsvirs** [comment] 2021-03-27 04:02
/ # df -B 1G / Filesystem 1G-blocks Used Available Use% Mounted on overlay
                                                             126       70        49             59% /

**Comment by Mahi0911** [comment] 2021-03-27 04:10
could you please post the docker file you are using @tsvirs

**Comment by tsvirs** [comment] 2021-03-27 07:54
![image](https://user-images.githubusercontent.com/19851229/112714277-a7aa3600-8f14-11eb-9f07-cb18465c139e.png)

**Comment by Mahi0911** [comment] 2021-03-27 07:57
I mean "Dockerfile"
OracleDatabase/SingleInstance/dockerfiles/19.3.0/Dockerfile

**Comment by tsvirs** [comment] 2021-03-27 08:16
# LICENSE UPL 1.0
#
# Copyright (c) 2018, 2020 Oracle and/or its affiliates.
#
# ORACLE DOCKERFILES PROJECT
# --------------------------
# This is the Dockerfile for Oracle Database 19c
# 
# REQUIRED FILES TO BUILD THIS IMAGE
# ----------------------------------
# (1) db_home.zip
#     Download Oracle Database 19c Enterprise Edition or Standard Edition 2 for Linux x64
#     from http://www.oracle.com/technetwork/database/enterprise-edition/downloads/index.html
#
# HOW TO BUILD THIS IMAGE
# -----------------------
# Put all downloaded files in the same directory as this Dockerfile
# Run: 
#      $ docker build -t oracle/database:19.3.0-${EDITION} . 
#
# Pull base image
# ---------------
FROM oraclelinux:7-slim as base

# Labels
# ------
LABEL "provider"="Oracle"                                               \
      "issues"="https://github.com/oracle/docker-images/issues"         \
      "volume.data"="/opt/oracle/oradata"                               \
      "volume.setup.location1"="/opt/oracle/scripts/setup"              \
      "volume.setup.location2"="/docker-entrypoint-initdb.d/setup"      \
      "volume.startup.location1"="/opt/oracle/scripts/startup"          \
      "volume.startup.location2"="/docker-entrypoint-initdb.d/startup"  \
      "port.listener"="1521"                                            \
      "port.oemexpress"="5500"

# Argument to control removal of components not needed after db software installation
ARG SLIMMING=true

# Environment variables required for this build (do NOT change)
# -------------------------------------------------------------
ENV ORACLE_BASE=/opt/oracle \
    ORACLE_HOME=/opt/oracle/product/19c/dbhome_1 \
    INSTALL_DIR=/opt/install \
    INSTALL_FILE_1="LINUX.X64_193000_db_home.zip" \
    INSTALL_RSP="db_inst.rsp" \
    CONFIG_RSP="dbca.rsp.tmpl" \
    PWD_FILE="setPassword.sh" \
    RUN_FILE="runOracle.sh" \
    START_FILE="startDB.sh" \
    CREATE_DB_FILE="createDB.sh" \
    SETUP_LINUX_FILE="setupLinuxEnv.sh" \
    CHECK_SPACE_FILE="checkSpace.sh" \
    CHECK_DB_FILE="checkDBStatus.sh" \
    USER_SCRIPTS_FILE="runUserScripts.sh" \
    INSTALL_DB_BINARIES_FILE="installDBBinaries.sh" \
    RELINK_BINARY_FILE="relinkOracleBinary.sh" \
    SLIMMING=$SLIMMING

# Use second ENV so that variable get substituted
ENV PATH=$ORACLE_HOME/bin:$ORACLE_HOME/OPatch/:/usr/sbin:$PATH \
    LD_LIBRARY_PATH=$ORACLE_HOME/lib:/usr/lib \
    CLASSPATH=$ORACLE_HOME/jlib:$ORACLE_HOME/rdbms/jlib

# Copy files needed during both installation and runtime
# -------------
COPY $SETUP_LINUX_FILE $CHECK_SPACE_FILE $INSTALL_DIR/
COPY $RUN_FILE $START_FILE $CREATE_DB_FILE $CONFIG_RSP $PWD_FILE $CHECK_DB_FILE $USER_SCRIPTS_FILE $RELINK_BINARY_FILE $ORACLE_BASE/

RUN chmod ug+x $INSTALL_DIR/*.sh && \
    sync && \
    $INSTALL_DIR/$CHECK_SPACE_FILE && \
    $INSTALL_DIR/$SETUP_LINUX_FILE && \
    rm -rf $INSTALL_DIR



#############################################
# -------------------------------------------
# Start new stage for installing the database
# -------------------------------------------
#############################################

FROM base AS builder

ARG DB_EDITION

# Copy DB install file
COPY --chown=oracle:dba $INSTALL_FILE_1 $INSTALL_RSP $INSTALL_DB_BINARIES_FILE $INSTALL_DIR/

# Install DB software binaries
USER oracle
RUN chmod ug+x $INSTALL_DIR/*.sh && \
    sync && \
    $INSTALL_DIR/$INSTALL_DB_BINARIES_FILE $DB_EDITION



#############################################
# -------------------------------------------
# Start new layer for database runtime
# -------------------------------------------
#############################################

FROM base

USER oracle
COPY --chown=oracle:dba --from=builder $ORACLE_BASE $ORACLE_BASE

USER root
RUN $ORACLE_BASE/oraInventory/orainstRoot.sh && \
    $ORACLE_HOME/root.sh

USER oracle
WORKDIR /home/oracle

HEALTHCHECK --interval=1m --start-period=5m \
   CMD "$ORACLE_BASE/$CHECK_DB_FILE" >/dev/null || exit 1

# Define default command to start Oracle Database. 
CMD exec $ORACLE_BASE/$RUN_FILE

**Comment by tsvirs** [comment] 2021-03-28 00:18
Dockerfile

**Comment by tsvirs** [comment] 2021-03-28 00:19
[Dockerfile.zip](https://github.com/oracle/docker-images/files/6216660/Dockerfile.zip)

**Comment by tsvirs** [comment] 2021-03-29 01:39
Still, no idea how to get through it.

**Comment by Mahi0911** [comment] 2021-03-29 05:09
it should not have happened on a clean install. The orainstRoot.sh script is only not created if an oraInventory is already present.

Is there any cached/dangling image ?

**Comment by tsvirs** [comment] 2021-03-29 08:46
=> [builder 2/2] RUN chmod ug+x /opt/install/*.sh &&     sync &&     /opt/install/installDBBinaries.sh ee                      85.7s 
 => [stage-2 1/3] COPY --chown=oracle:dba --from=builder /opt/oracle /opt/oracle                                               100.7s 
 => ERROR [stage-2 2/3] RUN /opt/oracle/oraInventory/orainstRoot.sh &&     /opt/oracle/product/19c/dbhome_1/root.sh  

Would you think it might be a permission problem? Because when in [stage-2 1/3], there were not any /opt/oracle directories have been created in my /opt/  .

**Comment by Mahi0911** [comment] 2021-03-29 09:14
$ docker builder prune
This removes build cache . Run this command and try building the image again

**Comment by tsvirs** [comment] 2021-03-29 12:08
WARNING! This will remove all dangling build cache. Are you sure you want to continue? [y/N] y
Deleted build cache objects:

Total reclaimed space: 87.99GB




 => [builder 2/2] RUN chmod ug+x /opt/install/*.sh &&     sync &&     /opt/install/installDBBinaries.sh ee                                                                      70.5s 
 => [stage-2 1/3] COPY --chown=oracle:dba --from=builder /opt/oracle /opt/oracle                                                                                                65.1s 
 => ERROR [stage-2 2/3] RUN /opt/oracle/oraInventory/orainstRoot.sh &&     /opt/oracle/product/19c/dbhome_1/root.sh                                                              0.8s 
------

**Comment by tsvirs** [comment] 2021-03-29 12:09
=> ERROR [stage-2 2/3] RUN /opt/oracle/oraInventory/orainstRoot.sh &&     /opt/oracle/product/19c/dbhome_1/root.sh                                                              0.8s 
------                                                                                                                                                                                
 > [stage-2 2/3] RUN /opt/oracle/oraInventory/orainstRoot.sh &&     /opt/oracle/product/19c/dbhome_1/root.sh:                                                                         
#13 0.715 /bin/sh: /opt/oracle/oraInventory/orainstRoot.sh: No such file or directory                                                                                                 
------                                                                                                                                                                                
executor failed running [/bin/sh -c $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh]: exit code: 127

ERROR: Oracle Database container image was NOT successfully created.
ERROR: Check the output and correct any reported problems with the build operation.

**Comment by Mahi0911** [comment] 2021-03-29 15:21
Are you available for a call on zoom ?

**Comment by Mahi0911** [comment] 2021-04-01 11:21
check the size of  " LINUX.X64_193000_db_home.zip " file and make sure the file is properly downloaded .
could you post the md5 sum .

**Comment by fuero** [comment] 2021-08-04 16:53
Same here.

The file's checksum seems alright:

```
$ sha256sum dockerfiles/19.3.0/LINUX.X64_193000_db_home.zip
ba8329c757133da313ed3b6d7f86c5ac42cd9970a28bf2e6233f3235233aa8d8  dockerfiles/19.3.0/LINUX.X64_193000_db_home.zip
```

It does seem like the installer crashes:
```
+ /opt/oracle/product/19c/dbhome_1/runInstaller -silent -force -waitforcompletion -responsefile /opt/install/db_inst.rsp -ignorePrereqFailure
Launching Oracle Database Setup Wizard...

[FATAL] [INS-32038] The operating system group (dba), specified for central inventory (oraInventory) ownership, is invalid.
   CAUSE: The user performing the installation (oracle) is not a member of the operating system group (dba).
   ACTION: Specify an operating system group that the installing user (oracle) is a member of. All the members of this operating system group will have write permission to the central inventory directory (oraInventory).
[WARNING] [INS-32055] The Central Inventory is located in the Oracle base.
   ACTION: Oracle recommends placing this Central Inventory in a location outside the Oracle base directory.
```

**Comment by fuero** [comment] 2021-08-04 17:56
Here's the log of the build attempt: `./buildContainerImage.sh -e -v 19.3.0 2>&1 | tee build.log`
[build.log.gz](https://github.com/oracle/docker-images/files/6933414/build.log.gz)

Changes against d648e8a915da1a72983c6dcbfd6280e81bb42762 to get more info from the installer and force it to use a larger volume (`--tmpdir / TMPDIR`):
[localchanges.diff.gz](https://github.com/oracle/docker-images/files/6933425/localchanges.diff.gz)

**Comment by johnlabarge** [comment] 2021-11-30 21:24
I'm having the same issue.

**Comment by futoyama** [comment] 2021-12-18 13:41
I had the same problem.
I used podman instead of docker and ran buildContainerImage.sh as a non-root user.
However, when I ran buildContainerImage.sh as root user, it terminated normally.

**Comment by sami-bsf** [comment] 2021-12-30 14:16
- Cleared docker image cache as above.
- Disabled Safari unzipping or "opening" downloads automatically.
- Downloaded the zip file again
-  it worked with `./buildContainerImage.sh -v 19.3.0 -s`

Re-zipping the folder after Safari unzipped it automatically broke it for me with this issue.

Not sure if it helps someone else on macOS or might help troubleshoot underlying issue.

**Comment by abhisbyk** [comment] 2022-05-24 10:24
@tsvirs  I am unable to reproduce this. This happens mostly because of the corrupted `LINUX.X64_193000_db_home.zip`. Please download this zip file again from the OTN. The `buildContainerImage.sh` script does the md5 checksum verification of the zip file automatically. The sample command is as follows:
`./buildContainerImage.sh -e -v 19.3.0`

Please update if the same problem persists. Thanks.

**Comment by abhisbyk** [comment] 2022-09-05 08:26
Closing this issue for now. Please reopen if this issue is encountered again.

**Closed by abhisbyk** 2022-09-05 08:26 UTC
Labels: more-info-required
