### ISSUE TITLE
Script orainstRoot.sh not found (21.3 - Enterprise Edition)

### ISSUE THREAD

**Issue by esloch** [oracle/docker-images#2591] opened 2023-03-15 00:22 UTC
``` 
$ podman --version
podman version 3.4.4

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.10
Release:        22.10
Codename:       kinetic

``` 
``` 
mv ~/Downloads/LINUX.X64_213000_db_home.zip docker-images/OracleDatabase/SingleInstance/dockerfiles/21.3.0/LINUX.X64_213000_db_home.zip
``` 
``` 
./buildContainerImage.sh -v 21.3.0 -e
``` 
Traceback
``` 
Launching Oracle Database Setup Wizard...

[FATAL] [INS-32038] The operating system group (dba), specified for central inventory (oraInventory) ownership, is invalid.
   CAUSE: The user performing the installation (oracle) is not a member of the operating system group (dba).
   ACTION: Specify an operating system group that the installing user (oracle) is a member of. All the members of this operating system group will have write permission to the central inventory directory (oraInventory).
[WARNING] [INS-32055] The Central Inventory is located in the Oracle base.
   ACTION: Oracle recommends placing this Central Inventory in a location outside the Oracle base directory.
Moved the install session logs to:
 /opt/oracle/oraInventory/logs/InstallActions2023-03-14_11-33-50PM
ds--> cf65d5f50de
[3/3] STEP 1/10: FROM 4a7fdce7245c8144e55989e775e89c21de72ac3a8f450eefa66bd3e2c3e34e8c
[3/3] STEP 2/10: USER oracle
--> bf9c8a27e28
[3/3] STEP 3/10: COPY --chown=oracle:dba --from=builder $ORACLE_BASE $ORACLE_BASE
dsghj--> f2ebac4f5dd
[3/3] STEP 4/10: USER root
--> 95000600189
[3/3] STEP 5/10: RUN $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh
/bin/sh: /opt/oracle/oraInventory/orainstRoot.sh: No such file or directory
Error: error building at STEP "RUN $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh": error while running runtime: exit status 127

ERROR: Oracle Database container image was NOT successfully created.
ERROR: Check the output and correct any reported problems with the build operation.

```

**Comment by gvenzl** [comment] 2023-03-15 01:07
Hi @esloch, could you please provide the entire output from the build script?
The error hints at an unsuccessful step earlier on.

**Comment by aditya059** [comment] 2023-04-05 07:24
Hi @esloch 
I tried the same on Ubuntu 22.04.2 LTS. I wasn't able to reproduce the issue. For me, the docker image built was successful.  Please provide the entire output from the build script.

**Comment by aditya059** [comment] 2023-04-07 05:47
Hi @esloch 

Closing this issue due to lack of information (build script output). Please reopen if you face the issue again

**Closed by aditya059** 2023-04-07 05:47 UTC
Labels: database

**Comment by esloch** [comment] 2023-04-07 11:55
N.P!
Thank you.

**Comment by 3ronco** [comment] 2024-07-24 08:23
Is there a solution to this?
As i'm facing the same problem.

**Comment by 3ronco** [comment] 2024-07-24 09:14
May you have a look at the log file? [InstallActions.tar.gz](https://github.com/user-attachments/files/16359912/InstallActions.tar.gz)

**Comment by oraclesean** [comment] 2024-07-24 13:06
The relevant pieces of the install logs are:
```
INFO:  [Jul 24, 2024 8:30:58 AM] Checking whether the given inventory location /opt/oracle/oraInventory is user home or not...
INFO:  [Jul 24, 2024 8:30:58 AM] User oracle belongs to following groups: [ErrorException]
SEVERE:  [Jul 24, 2024 8:30:58 AM] [FATAL] [INS-32038] The operating system group (dba), specified for central inventory (oraInventory) ownership, is invalid.
   CAUSE: The user performing the installation (oracle) is not a member of the operating system group (dba).
   ACTION: Specify an operating system group that the installing user (oracle) is a member of. All the members of this operating system group will have write permission to the central inventory directory (oraInventory).
WARNING:  [Jul 24, 2024 8:30:58 AM] [WARNING] [INS-32055] The Central Inventory is located in the Oracle base.
   ACTION: Oracle recommends placing this Central Inventory in a location outside the Oracle base directory.
INFO:  [Jul 24, 2024 8:30:58 AM] Advice is ABORT
INFO:  [Jul 24, 2024 8:30:58 AM] Adding ExitStatus INVALID_USER_INPUT to the exit status set
...
INFO:  [Jul 24, 2024 8:30:58 AM] The inventory does not exist, but the location of the inventory is known: /opt/oracle/oraInventory
INFO:  [Jul 24, 2024 8:30:58 AM] Finding the most appropriate exit status for the current application
INFO:  [Jul 24, 2024 8:30:58 AM] Exit Status is -2
INFO:  [Jul 24, 2024 8:30:58 AM] Shutdown Oracle Database 19c Installer
INFO:  [Jul 24, 2024 8:30:58 AM] Unloading Setup Driver
```
...and:
```
[FATAL] [INS-32038] The operating system group (dba), specified for central inventory (oraInventory) ownership, is invalid.
   CAUSE: The user performing the installation (oracle) is not a member of the operating system group (dba).
   ACTION: Specify an operating system group that the installing user (oracle) is a member of. All the members of this operating system group will have write permission to the central inventory directory (oraInventory).
```
Oracle expects the `oracle` user to be a member of the `dba` group. That group isn't found during the installation, and it fails. This is either a failure in the image build process (the steps prior to the database software installation run the preinstall RPM, which creates the necessary users and groups within the container) or something odd in the host environment. But it seems more likely (since this isn't happening to everyone) that the environment is missing something.

See if this helps: [https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md](https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md).

**Comment by yunus-qureshi** [comment] 2024-07-24 14:28
Thanks @oraclesean 
This might help too
https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance#building-the-container-images-using-podman

**Comment by 3ronco** [comment] 2024-07-24 19:51
@yunus-qureshi 
Thanks that did the trick. Setup the environment with:
```
export BUILDAH_FORMAT=docker;
export BUILDAH_ISOLATION=chroot;
```
Although i now get two warnings at that spot:
```
[WARNING] [INS-32055] The Central Inventory is located in the Oracle base.
   ACTION: Oracle recommends placing this Central Inventory in a location outside the Oracle base directory.
[WARNING] [INS-13014] Target environment does not meet some optional requirements.
   CAUSE: Some of the optional prerequisites are not met. See logs for details. installActions2024-07-24_06-19-44PM.log
   ACTION: Identify the list of failed prerequisite checks from the log: installActions2024-07-24_06-19-44PM.log. Then either from the log file or from installation manual find the appropriate configuration to meet the prerequisites and fix it manually.
The response file for this session can be found at:
 /opt/oracle/product/19c/dbhome_1/install/response/db_2024-07-24_06-19-44PM.rsp
```
These aren't fatal and the build process continues.
In the AfterMath the question is how did my last image build (six days ago) managed it to build successfully without those? It seems that with the newer revision of `buildContainerImage.sh` these are mandatory now. Anyway it works now. Thank you! 🙏

**Comment by 3ronco** [comment] 2024-07-24 19:54
PS: I guess you know that enforcing `BUILDAH_ISOLATION` onto _chroot level_ can be dangerous _when exported globally_ (especially when these settings remain after `buildContainerImage.sh` has run) as it affects any image build running in that shell (& child processes) even for those images intended to be build rootless and even worse containers (!) as `podman run` checks that variable as well.
If i may make a suggestion you should consider using `podman build ... --isolation=chroot` as a default in `buildContainerImage.sh` script for the main image only.

**Comment by 3ronco** [comment] 2024-07-31 11:08
For those who don't want to use _chroot_ level via `BUILDAH_ISOLATION`. I found the reason why the _podman_ build with `buildContainerImage.sh` failed. First, _chroot_ is not necessarily a requirement for rootless _podman_ builds when building an _oracle database image_.
The strange error message stating that the _oracle_ user must be a member of the _dba_ group pointed directly to the user _namespace mapping_. Since that stuff is happening inside the build stage and once _oracle_ (a user of the container) is assigned to a group it should work but in a _podman_ rootless build that user is mapped to your user on the host building the image (!) which is done with the _rootlesskit_ (`etc/subid` & `etc/subgid`)
This needs to work in both directions not only from inside podman's build stage but also from the host which means your user (building the container) needs to be queryable from `getent passwd` for _podman_ (!)
Any other additional user mapping (for a system linux user besides the _namespace mapping_ done by _podman_) eg. from a remote directory (LDAP, AD, NFS, etc.) won't work unless the user appears directly in the kernel's userlist. So what the error basically says is the _oracle_ user is a member of _dba_ but your mapped host user isn't.
In my case the user was mapped through _winbind_ on my host for which a workaround is possible when using `winbind enum users = yes` in `smb.conf` to appear in _passwd_ list.
