### ISSUE TITLE
Creating and starting Database as part of Image build

### ISSUE THREAD

**Issue by SRINIVASREDDYPV** [oracle/docker-images#478] opened 2017-07-14 10:54 UTC
Currently as part of  database 12.2.0.1 base image build, Database will be created and started during Docker run. 
We wanted to include this as part of build process because we have to compile 10k+ packages and populate the data for tables during build itself to avoid the time taken during Docker Run.
To do this we have created a  shell script which will create database, starts database, creates schema and compiles the required packages and the same will be called in the docker file using run command.

Image is getting created successfully but i am not able to run the image because i have not given any input to CMD command in docker file. So i created a dummy shell script to echo successful DB creation and given same dummy script file as input to CMD. 

Now i am able to run the image but when i inspect the container, i couldn't see DB running in it.

**Am i doing anything wrong ?**

**@Djelibeybi @gvenzl ,Please suggest me if you have some time.**

(Build output removed because it is irrelevant to the question).

**Comment by Djelibeybi** [comment] 2017-07-14 11:09
Your `CMD` command will have to run a script that _actually starts the database_.

**Comment by SRINIVASREDDYPV** [comment] 2017-07-14 16:13
@Djelibeybi , Thank you for your quick response.
For our product, The compilation of pl/sql packages in a database schema will take 24 hours.
So you are telling me to compile the packages once the container is up(i.e DB is up). 
We were thinking that, we can compile all the packages during image build itself So that container will be up and running in a fraction of time.
Is there any alternative for our requirement or our idea is incorrect ?

**Comment by Djelibeybi** [comment] 2017-07-14 16:28
Wait, why do you have a database inside your container? You should be using the existing database container (or an external database) and when your product starts, it should compile the PL/SQL required. 

If this is for internal use only, there are some shortcuts we could discuss, but if this is intended for external end-user/customer use, then your image must only contain a single product.

**Comment by SRINIVASREDDYPV** [comment] 2017-07-14 16:45
Basically we want to setup entire product environment in one docker image and share it with different development groups, testing teams etc.
Yes it is for internal use only not for the customer.

**Comment by Djelibeybi** [comment] 2017-07-14 17:01
Right, ok.

In that case, you will need to have a single `RUN` directive in your `Dockerfile` that configures and starts the database, compiles your PL/SQL and then gracefully _shuts down_ the database. 

The concept I think that's missing here is that a `docker build` process is a series of discrete steps. This is not a VM. The build process is not a single process. It essentially creates and destroys individual containers for each directive and only runs the processes required by a single directive at a time.

If you start the database in one `RUN` directive, it will no longer be running in the next directive.

So, in order for the database to be started when a container based off this image is started with `docker run`, your `CMD` directive in the _same_ Dockerfile has to start the _same_ database up. This is because the `RUN` command only occurs during `docker build`. When you start a container using `docker run` it only starts the process or script defined by either an `ENTRYPOINT` or `CMD` directive.

**Comment by SRINIVASREDDYPV** [comment] 2017-07-14 17:25
I tried writing docker file by extending base image which will have one RUN directive which creates database, schema,compile the packages and shut down the database.

But when i run the image, i could not find the ORACLE_SID folder which would have been created during build. So i am not able to start the Database.

My CMD file has below code to start the database.

if [ -d $ORACLE_BASE/oradata/$ORACLE_SID ]; then
 # Start database
   $ORACLE_BASE/$START_FILE;
fi;

**Comment by Djelibeybi** [comment] 2017-07-14 18:14
I'm closing this issue because we need to discuss this internally.

**Closed by Djelibeybi** 2017-07-14 18:14 UTC
Labels: database, help wanted, question

**Comment by sporkisfaster** [comment] 2018-02-28 21:45
Was there a resolution for this question? I have the same issue as I need to be able to generate even the default database at "docker build" time rather than "docker run" time. The reason for this is that I am writing an API for my company that spins up these containers on demand, runs tests against them, then throws them away. Right now this takes a long time as it takes quite a while to generate the database when using "docker run". I know I could spin up containers ahead of time and stop them but that doesn't help our particular use case.

**Comment by gvenzl** [comment] 2018-02-28 23:46
Hi @sporkisfaster, you can indeed accomplish that. However, you will have to get rid of the `VOLUME` instruction which can't be undone in a child image. See https://github.com/oracle/docker-images/tree/master/OracleDatabase/samples/prebuiltdb for the steps required.

**Comment by sporkisfaster** [comment] 2018-02-28 23:47
Fantastic. Thanks!

**Comment by nickperkinslondon** [comment] 2021-02-02 15:42
So, this has never really been resolved, has it?
The holy grail, in this case, is a way to use only Dockerfiles to achieve a "pre-built" oracle database
( pre-configured and loaded with data, baked-in to the image, not using a volume ).

The problem is that the database does not actually run at any point in the build process.
Is it actually possible to use a RUN directive to start-up the database, do stuff, and then shut-down?
I can't find any examples of that.  Has anyone done it?

If this cannot be done at build-time, then we are left with a much more ad-hoc system of running containers, using scripts to do stuff, and then using "docker commit" to create the next image.  That works, but it's not organized like a Dockerfile, and doesn't use layers the way a Dockerfile does.  It seems like it could get confusing and disorganized really fast.

It would be so much better if could somehow "do stuff" to the database during the build process!

**Comment by starwarsfan** [comment] 2024-05-28 08:39
One would name it a hack, others would name it a trick but anyway, I wrote this helper function to initialize the database during the image build. That's a helper function, which is called before the image is built (19.3 ee edition):

```bash
# ---------------------------------------------------------------------------
# To initialize the database right during image build, $ORACLE_BASE/$RUN_FILE
# must be executed. But the original version can't be used as it is not
# exiting at the end, so we need to use some tricks. ;-)
#
# The following steps will be added to the main build step on the Dockerfile.
# That's necessary to keep the image as small as possible because if this is
# done on a separate Dockerfile based on the official one, a huge part of the
# Docker layer will be duplicated. Even with this trick the image will be
# nearly 10G in size. :-/
#
# Here are the additional steps:
# 1. Create a copy of $ORACLE_BASE/$RUN_FILE by removing the last four lines.
# 2. Make the copy executable
# 3. Start the script to trigger exactly one initial database run, which will
#    initialize everything.
patchDockerfile() {
    local dockerfileModifications
    echo "Patching Dockerfile ${oraDBVersion}/Dockerfile"
    read -r -d '' dockerfileModifications <<'EOF'
tac $ORACLE_BASE/$RUN_FILE | sed '1,4 d' | tac > $ORACLE_BASE/runOracleInitialization.sh \&\& chmod +x $ORACLE_BASE/runOracleInitialization.sh \&\& $ORACLE_BASE/runOracleInitialization.sh
EOF
    sed -i \
        -e "s#\(\$ORACLE_HOME/rdbms/jlib\).*\$#\1 \\\\\n    ORACLE_PWD=${defaultDBPassword}#g" \
        -e "s#\(\.bashrc\)#\1 \\\\\n \&\& ${dockerfileModifications}#g" \
        ${oraDBVersion}/Dockerfile
    echo " -> Done"
}
```
