### ISSUE TITLE
Having a single generic folder under OracleDatabase/SingleInstance/dockerfiles for newer releases (from 20c) moving forward

### ISSUE THREAD

**Issue by ghost** [oracle/docker-images#1373] opened 2019-09-18 08:38 UTC
1. There is a lot of code duplication across folders of different releases such 18.3.0 and 19.3.0.
2. checkDBStatus.sh, checkSpace.sh, createDB.sh, installDBBinaries.sh, runOracle.sh, runUserScripts.sh, setPassword.sh and startDB.sh are identical between the 2 folders.
3. Differences in the remaining files are mostly version related which can be handled by making use of the version passed by user during docker image creation.
4. A single checksum file can be maintained for all future releases instead of having sets of checksum files in each folder. (Also, since the same goldimage is used for EE and SE, there is no need to maintain 2 checksum files, names checksum.ee and checksum.se2)

**Comment by gvenzl** [comment] 2022-03-10 16:37
Duplicate of #1201.

**Closed by gvenzl** 2022-03-10 16:37 UTC
Labels: enhancement, database
