### ISSUE TITLE
checkDBStatus.sh: oracle/database:18.4.0-xe container healthy error with  multiple pluggable database

### ISSUE THREAD

**Issue by antoninoromeo** [oracle/docker-images#1076] opened 2018-12-11 10:24 UTC
After creation of XEPDB2:
create pluggable database xepdb2 admin user pdb_adm identified by Oradoc_db1
  file_name_convert=('/opt/oracle/oradata/XE/pdbseed','/opt/oracle/oradata/XE/XEPDB2');

alter pluggable database xepdb2 open read write;
alter pluggable database all save state;

select vp.name, vp.open_mode from v$pdbs vp:
PDB$SEED	READ ONLY
XEPDB1	READ WRITE
XEPDB2	READ WRITE

container status became unhealthy  due the checkDBStatus.sh check:
.......................
`ORACLE_PDB="`ls -dl $ORACLE_BASE/oradata/$ORACLE_SID/*/ | grep -v pdbseed | awk '{print $9}' | cut -d/ -f6`"`
and
`# Check Oracle DB status and store it in status
status=`su -p -c - oracle "sqlplus -s / as sysdba" << EOF
   set heading off;
   set pagesize 0;
   SELECT open_mode FROM v\\$pdbs WHERE name COLLATE BINARY_CI = '$ORACLE_PDB';
   exit;
EOF``

I changed in:
`ORACLE_PDB="`ls -dl $ORACLE_BASE/oradata/$ORACLE_SID/*/ | grep -v pdbseed | awk '{print $9}' | cut -d/ -f6| xargs -I{} echo \"'{}',\"`" `
and
``status=`su -p -c - oracle "sqlplus -s / as sysdba" << EOF
    set heading off;
    set pagesize 0;
    SELECT distinct(open_mode) FROM v\\$pdbs WHERE name COLLATE BINARY_CI in ( $ORACLE_PDB '');
  exit;
`EOF``

and now docker container status is again healthy.

**Comment by gvenzl** [comment] 2018-12-11 16:53
Duplicate of #1041.

**Closed by gvenzl** 2018-12-11 16:53 UTC
Labels: database, duplicate
