### ISSUE TITLE
why docker commit can's save the persistent oracle instance (12.2)

### ISSUE THREAD

**Issue by jerrywangatoracle** [oracle/docker-images#361] opened 2017-04-25 11:20 UTC
###  i want to save a container with oracle 12c instance to a image , but afte i start new container with the new created image, no database was saved.

```
[root@host1 ~]# docker ps -a
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                      PORTS                NAMES
ec967c8134fd        oracle/database:12.2.0.1-ee   "/bin/sh -c 'exec $OR"   5 days ago          Up 35 minutes               1521/tcp, 5500/tcp   jerrydb122

[root@host1 ~]# docker exec -ti ec967c8134fd bash

******* we can see there is instance was running
[oracle@ec967c8134fd ~]$ ps -ef|grep ora_                                                                                                                                  
oracle      19     1  0 10:29 ?        00:00:00 ora_pmon_db122
oracle      21     1  0 10:29 ?        00:00:00 ora_clmn_db122
。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
oracle     493     1  0 10:43 ?        00:00:00 ora_w007_db122
oracle     692   676  0 11:05 ?        00:00:00 grep --color=auto ora_
[oracle@ec967c8134fd ~]$ sqlplus '/as sysdba'
SQL*Plus: Release 12.2.0.1.0 Production on Tue Apr 25 11:06:11 2017
Copyright (c) 1982, 2016, Oracle.  All rights reserved.
Connected to:
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
SQL> show pdbs;

    CON_ID CON_NAME                       OPEN MODE  RESTRICTED
---------- ------------------------------ ---------- ----------
         2 PDB$SEED                       READ ONLY  NO
         3 DB122PDB                       READ WRITE NO
SQL> exit
Disconnected from Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
[oracle@ec967c8134fd ~]$ cd /opt/oracle
[oracle@ec967c8134fd oracle]$ du -sk oradata
3427580 oradata
[oracle@ec967c8134fd oracle]$ 

#### after i close the database ,I created two images ( one is when container was stop, one is  alive ) 

[root@host1 ~]# docker commit ec967c8134fd db122_withdb_con_alive
sha256:69ed60dc0fd02d4407f95061d112e52107fd40fa5674796335e8ebd9449e8f38

[root@host1 ~]# docker commit ec967c8134fd db122_withdb_con_stop 
sha256:d55ee7d646ac4863f3003b770746bbee17c66b1b1e69b447e28d598ba15d14e2


[root@host1 ~]# docker images
REPOSITORY                                                                       TAG                 IMAGE ID            CREATED             SIZE
db122_withdb_con_stop                                                            latest              d55ee7d646ac        38 minutes ago      14.85 GB
db122_withdb_con_alive                                                           latest              69ed60dc0fd0        39 minutes ago      14.85 GB
latest_db122_withdb                                                              latest              da9891eabfa4        5 days ago          14.85 GB
mydb122_with_sql                                                                 latest              ce4e8d002c07        5 days ago          14.85 GB
oracle/database                                                                  12201EE_withDB      bdbf078a8ad2        5 days ago          14.85 GB
oracle/database                                                                  12.2.0.1-ee         b6c754881f51        6 days ago          14.82 GB

### but when i run a container either on one of the new created image, no db ( no datafiles ) can be seen in the container

[root@host1 ~]# docker run -it  d55ee7d646ac bash
[oracle@603f8c047e6a ~]$ ps -ef|grep ora_
oracle      18     1  0 10:27 ?        00:00:00 grep --color=auto ora_
[oracle@603f8c047e6a ~]$ cd /opt/oracle

[oracle@603f8c047e6a oracle]$ sqlplus '/as sysdba'
SQL*Plus: Release 12.2.0.1.0 Production on Tue Apr 25 10:28:03 2017
Copyright (c) 1982, 2016, Oracle.  All rights reserved.
Connected to an idle instance.
SQL> startup;
ORA-01078: failure in processing system parameters
LRM-00109: could not open parameter file '/opt/oracle/product/12.2.0.1/dbhome_1/dbs/initdb122.ora'
SQL> exit
Disconnected
[oracle@603f8c047e6a oracle]$ cd /opt/oracle
[oracle@603f8c047e6a oracle]$ du -sk oradata
0       oradata
```

**Comment by gvenzl** [comment] 2017-04-26 22:28
Duplicate of issue #269: Commit to image and restart of container provokes "ORA-01034: ORACLE not available"

**Closed by gvenzl** 2017-04-26 22:28 UTC
Labels: database, duplicate
