### ISSUE TITLE
can't run the racnode1

### ISSUE THREAD

**Issue by withqingshao** [oracle/docker-images#1477] opened 2020-01-03 03:41 UTC
PRVG-10048 : Name "racnode1" was not resolved to an address of the
            specified type by name servers o"127.0.0.11"

**Comment by mark-au** [comment] 2020-01-13 04:22
I'm guessing you are trying to build one of the OracleRealApplicationClusters images but which version are you having trouble with?

**Comment by mark-au** [comment] 2020-01-13 04:25
Duplicate of #1475

**Closed by mark-au** 2020-01-13 04:25 UTC
Labels: more-info-required
