### ISSUE TITLE
Error when building Oracle Database 18.3.0 image on WSL

### ISSUE THREAD

**Issue by SIkebe** [oracle/docker-images#962] opened 2018-08-11 05:29 UTC
Building Oracle Database 18.3.0 image on Windows Subsystem for Linux fails as follows. Am I missing something?
```
PS C:\GitHub\docker-images\OracleDatabase\SingleInstance\dockerfiles> wsl ./buildDockerImage.sh -v 18.3.0 -e
Checking if required packages are present and valid...
LINUX.X64_180000_db_home.zip: OK
==========================
DOCKER info:
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 12
Server Version: 17.03.2-ce
Storage Driver: overlay2
 Backing Filesystem: <unknown>
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Kernel Version: 4.4.0-17134-Microsoft
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.93 GiB
Name: DESKTOP-OH5ODU7
ID: W5QK:DBBR:HLRI:UUWX:HTTJ:HRCX:D2M5:O5VM:6KV7:YAJZ:3HTF:EYS2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: intestine
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpu shares support
WARNING: No cpuset support
==========================
Building image 'oracle/database:18.3.0-ee' ...
Sending build context to Docker daemon 4.565 GB
Step 1/17 : FROM oraclelinux:7-slim
 ---> 149bf1b8baa0
Step 2/17 : MAINTAINER Gerald Venzl <gerald.venzl@oracle.com>
 ---> Running in ac0f6242a3e8
 ---> 351a1d190381
Removing intermediate container ac0f6242a3e8
Step 3/17 : ENV ORACLE_BASE /opt/oracle ORACLE_HOME /opt/oracle/product/18c/dbhome_1 INSTALL_FILE_1 "LINUX.X64_180000_db_home.zip" INSTALL_RSP "db_inst.rsp" CONFIG_RSP "dbca.rsp.tmpl" PWD_FILE "setPassword.sh" RUN_FILE "runOracle.sh" START_FILE "startDB.sh" CREATE_DB_FILE "createDB.sh" SETUP_LINUX_FILE "setupLinuxEnv.sh" CHECK_SPACE_FILE "checkSpace.sh" CHECK_DB_FILE "checkDBStatus.sh" USER_SCRIPTS_FILE "runUserScripts.sh" INSTALL_DB_BINARIES_FILE "installDBBinaries.sh"
 ---> Running in 52d8cda71c1e
 ---> 20effa92d0e9
Removing intermediate container 52d8cda71c1e
Step 4/17 : ENV INSTALL_DIR $ORACLE_BASE/install PATH $ORACLE_HOME/bin:$ORACLE_HOME/OPatch/:/usr/sbin:$PATH LD_LIBRARY_PATH $ORACLE_HOME/lib:/usr/lib CLASSPATH $ORACLE_HOME/jlib:$ORACLE_HOME/rdbms/jlib
 ---> Running in 6b77a712292e
 ---> d8f6add5a8dc
Removing intermediate container 6b77a712292e
Step 5/17 : COPY $INSTALL_FILE_1 $INSTALL_RSP $SETUP_LINUX_FILE $CHECK_SPACE_FILE $INSTALL_DB_BINARIES_FILE $INSTALL_DIR/
 ---> 0b1b1d44b34f
Removing intermediate container 511341b128d7
Step 6/17 : COPY $RUN_FILE $START_FILE $CREATE_DB_FILE $CONFIG_RSP $PWD_FILE $CHECK_DB_FILE $USER_SCRIPTS_FILE $ORACLE_BASE/
 ---> 56bc8ff8c1d8
Removing intermediate container 787c79301b2b
Step 7/17 : RUN chmod ug+x $INSTALL_DIR/*.sh &&     sync &&     $INSTALL_DIR/$CHECK_SPACE_FILE &&     $INSTALL_DIR/$SETUP_LINUX_FILE
 ---> Running in 693e94ddf8d8
Loaded plugins: ovl
Resolving Dependencies
--> Running transaction check
---> Package openssl.x86_64 1:1.0.2k-12.0.1.el7 will be installed
/opt/oracle/install/setupLinuxEnv.sh: line 25:    21 Segmentation fault      (core dumped) yum -y install oracle-database-preinstall-18c unzip tar openssl
Removing intermediate container 693e94ddf8d8
The command '/bin/sh -c chmod ug+x $INSTALL_DIR/*.sh &&     sync &&     $INSTALL_DIR/$CHECK_SPACE_FILE &&     $INSTALL_DIR/$SETUP_LINUX_FILE' returned a non-zero code: 139

ERROR: Oracle Database Docker Image was NOT successfully created.
ERROR: Check the output and correct any reported problems with the docker build operation.
PS C:\GitHub\docker-images\OracleDatabase\SingleInstance\dockerfiles>
```

**Comment by gvenzl** [comment] 2018-08-22 21:04
Hi @SIkebe,

The `yum` binary is dying when installing RPM packages:
```
/opt/oracle/install/setupLinuxEnv.sh: line 25:    21 Segmentation fault      (core dumped) yum -y install oracle-database-preinstall-18c unzip tar openssl
Removing intermediate container 693e94ddf8d8
```

**Comment by gurbelunder** [comment] 2018-08-24 15:31
Hi everybody,

I get the same by creating a new 12.2.0.1 docker image, but of course with the matching package to 12.2.0.1:

`/opt/oracle/install/setupLinuxEnv.sh: line 24:    19 Bus error               (core dumped) yum -y install oracle-database-server-12cR2-preinstall unzip tar openssl`

What is the fix here?

Thanks and regards,
David

**Comment by gvenzl** [comment] 2018-09-14 07:28
You will have to find out why `yum` core dumps. Unfortunately there is not much more that we can do here. Perhaps the Windows forums can be of help here?

**Comment by gurbelunder** [comment] 2018-09-14 07:29
Why could the Windows Forums help when the yum core in Oracle linux dumps? It dumps in the standard image which will be used by your scripts, the oracle-linux-slim image...

**Comment by gvenzl** [comment] 2018-09-14 08:26
Hm, which Linux and Docker version are you using where it core dumps?
I cannot reproduce it neither on OL7.5, Docker 18.03 nor on Mac OS, Docker 18.06.

I'm also reassigning it to @Djelibeybi given that this is an underlying Linux/`yum` issue and nothing to do with the scripts/database itself.

**Comment by gurbelunder** [comment] 2018-09-14 08:38
I think there was just an issue in the oraclelinux:7-slim image which comes from official docker store and it just matched here and not more 💃

**Comment by gvenzl** [comment] 2018-09-14 08:54
So this issue is resolved for you and can be closed?

**Comment by gurbelunder** [comment] 2018-09-14 08:55
For me it is resolved. Don't know, what the thread creator says ;)

**Comment by gvenzl** [comment] 2018-09-14 08:57
True, let's wait for @SIkebe to tell us first whether his issue is also resolved :)

**Comment by gvenzl** [comment] 2018-11-01 11:47
Closing assuming this issue is resolved.

**Closed by gvenzl** 2018-11-01 11:47 UTC
Labels: database, more-info-required
