### ISSUE TITLE
Failure occurred during the database creation when start the first RAC container

### ISSUE THREAD

**Issue by anti996sz** [oracle/docker-images#1146] opened 2019-02-09 13:24 UTC
when start the first RAC container, the contailer log stoped at:

...
02-09-2019 10:54:14 UTC :  : Checking Cluster Status
02-09-2019 10:54:14 UTC :  : Checking Cluster
02-09-2019 10:54:14 UTC :  : Cluster Check passed
02-09-2019 10:54:14 UTC :  : Cluster Check went fine
02-09-2019 10:54:17 UTC :  : MGMTDB Check went fine
02-09-2019 10:54:17 UTC :  : CRSD Check went fine
02-09-2019 10:54:17 UTC :  : CSSD Check went fine
02-09-2019 10:54:18 UTC :  : EVMD Check went fine
02-09-2019 10:54:18 UTC :  : Removing /tmp/cluvfy_check.txt as cluster check has passed
02-09-2019 10:54:18 UTC :  : Generating DB Responsefile Running DB creation
02-09-2019 10:54:18 UTC :  : Running DB creation
02-09-2019 11:10:04 UTC :  : Checking DB status
02-09-2019 11:10:26 UTC : : ORCLCDB is not up and running on racnode1
02-09-2019 11:10:27 UTC : : Error has occurred in Grid Setup, Please verify!

**Comment by scottwan** [comment] 2019-02-09 13:27
[RAC on Docker log2.txt](https://github.com/oracle/docker-images/files/2847822/RAC.on.Docker.log2.txt)

**Comment by scottwan** [comment] 2019-02-09 13:30
`# docker info`
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.35-1818.3.3.el7uek.x86_64
Operating System: Oracle Linux Server 7.6
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.805GiB
Name: docker.example.com
ID: THEQ:KNC2:H2I7:OZWT:7OVI:HMAE:32KM:ESTL:ZNZO:IZDJ:P3LA:KO57
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 com.docker.security.seccomp=enabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Unlicensed Enterprise Engine

**Comment by psaini79** [comment] 2019-02-09 16:13
I looked at the logs and it seems DB creation failed. Please provide me logs from the container. Please Execute following steps and provide me the logs:
docker exec -i -t -u root racnode1 /bin/bash
/u01/app/oracle/diag/rdbms/ORCLDB/ORCLDB/trace
$DB_HOME/cfgtoollogs/dbca

zip the files and upload.

**Comment by scottwan** [comment] 2019-02-10 01:52
[trace.zip](https://github.com/oracle/docker-images/files/2848457/trace.zip)

[dbca.zip](https://github.com/oracle/docker-images/files/2848459/dbca.zip)

**Comment by psaini79** [comment] 2019-02-10 08:46
Thanks for uploading the files. I looked at them and it seems Oracle instance crashed during DB creation. Also, few processes did not start.

[ 2019-02-09 16:45:11.421 UTC ] [WARNING] ORA-00443: background process "LMHB" did not start

[ 2019-02-09 16:45:16.832 UTC ] [FATAL] ORA-01034: ORACLE not available

DBCA_PROGRESS : 27%
DBCA_PROGRESS : 100%
[ 2019-02-09 16:45:49.219 UTC ] [FATAL] ORA-01034: ORACLE not available

I looked at alert.log and it seems some issues in your docker env and container setup as I tested on my machine and I am unable to reproduce these errors. I found following errors in alert.log:

2019-02-09T16:33:46.786977+00:00
Errors in file /u01/app/oracle/diag/rdbms/orclcdb/ORCLCDB1/trace/ORCLCDB1_ora_6434.trc:
ORA-27167: Attempt to determine if Oracle binary image is stored on remote server failed
ORA-27300: OS system dependent operation:parse_df failed with status: 2
ORA-27301: OS failure message: No such file or directory
ORA-27302: failure occurred at: parse failed

Please provide details:
Execute following commands from Docker Host:

docker images
docker info
uname -a
cat /etc/oracle-release or distribution details which you are using along with version
systemctl status docker
df -h
blkid
free -g

**Comment by scottwan** [comment] 2019-02-10 14:50
```# docker images
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
oracle/database-rac   18.3.0              5857cada56bb        6 days ago          32GB
oraclelinux           7-slim              c3d869388183        3 weeks ago         117MB```

**Comment by scottwan** [comment] 2019-02-10 14:57
```
# uname -a
Linux docker.example.com 4.14.35-1818.3.3.el7uek.x86_64 #2 SMP Mon Sep 24 14:45:01 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux

# cat /etc/oracle-release
Oracle Linux Server release 7.6
```

**Comment by scottwan** [comment] 2019-02-10 14:58
```
# systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: active (running) since Sat 2019-02-09 23:05:13 CST; 20h ago
     Docs: https://docs.docker.com
 Main PID: 15327 (dockerd)
    Tasks: 13
   Memory: 59.4M
   CGroup: /system.slice/docker.service
           └─15327 /usr/bin/dockerd --cpu-rt-runtime=950000 --cpu-rt-period=1000000 --exec-opt=native.cgroupdriver=systemd

Feb 09 23:05:12 docker.example.com dockerd[15327]: time="2019-02-09T23:05:12.542380353+08:00" level=info msg="Default bridge (do...dress"
Feb 09 23:05:12 docker.example.com dockerd[15327]: time="2019-02-09T23:05:12.945207078+08:00" level=info msg="Loading containers: done."
Feb 09 23:05:13 docker.example.com dockerd[15327]: time="2019-02-09T23:05:13.006357957+08:00" level=warning msg="Not using nativ...erlay2
Feb 09 23:05:13 docker.example.com dockerd[15327]: time="2019-02-09T23:05:13.007100523+08:00" level=info msg="unable to lookup l...uster"
Feb 09 23:05:13 docker.example.com dockerd[15327]: time="2019-02-09T23:05:13.007145632+08:00" level=info msg="Docker daemon" com...8.09.1
Feb 09 23:05:13 docker.example.com dockerd[15327]: time="2019-02-09T23:05:13.007164471+08:00" level=info msg="starting telemetry service"
Feb 09 23:05:13 docker.example.com dockerd[15327]: time="2019-02-09T23:05:13.007400455+08:00" level=info msg="Daemon has complet...ation"
Feb 09 23:05:13 docker.example.com dockerd[15327]: time="2019-02-09T23:05:13.032404078+08:00" level=info msg="API listen on /var....sock"
Feb 09 23:05:13 docker.example.com systemd[1]: Started Docker Application Container Engine.
Feb 09 23:09:30 docker.example.com dockerd[15327]: time="2019-02-09T23:09:30.112152083+08:00" level=error msg="Handler for POST ...ridge"
Hint: Some lines were ellipsized, use -l to show in full.
```

**Comment by scottwan** [comment] 2019-02-10 15:00
```
# df -h
Filesystem           Size  Used Avail Use% Mounted on
devtmpfs             3.9G     0  3.9G   0% /dev
tmpfs                4.0G     0  4.0G   0% /dev/shm
tmpfs                4.0G   17M  3.9G   1% /run
tmpfs                4.0G     0  4.0G   0% /sys/fs/cgroup
/dev/mapper/ol-root   50G   18G   33G  36% /
/dev/sda1           1014M  224M  791M  23% /boot
/dev/mapper/ol-home   62G   33G   29G  53% /var/lib/docker
tmpfs                800M   12K  800M   1% /run/user/42
overlay               62G   33G   29G  53% /var/lib/docker/overlay2/46152c005aaf5cd34bedbc16f70287ed5143c26a4099f410c30a486c087c94e2/merged
tmpfs                800M     0  800M   0% /run/user/0

# blkid
/dev/sda1: UUID="477f8194-7c21-41d3-a38e-e56e321d0f54" TYPE="xfs"
/dev/sda2: UUID="pIIYNL-6ZL4-Uyho-IbvC-wnzu-v36n-fKcHqq" TYPE="LVM2_member"
/dev/sdb: TYPE="oracleasm"
/dev/sdc: TYPE="oracleasm"
/dev/mapper/ol-root: UUID="6f78ea28-e7f2-47f6-816e-1f598e350728" TYPE="xfs"
/dev/mapper/ol-swap: UUID="b272ffaf-3b67-4edc-8c6f-3ce59c9995bd" TYPE="swap"
/dev/mapper/ol-home: UUID="92c653de-7877-4000-94bc-08e9c698d269" TYPE="xfs"

# free -g
              total        used        free      shared  buff/cache   available
Mem:              7           2           1           1           3           4
Swap:             7           1           6
```

**Comment by scottwan** [comment] 2019-02-10 15:03
```
# df -h
Filesystem           Size  Used Avail Use% Mounted on
devtmpfs             3.9G     0  3.9G   0% /dev
tmpfs                4.0G     0  4.0G   0% /dev/shm
tmpfs                4.0G   17M  3.9G   1% /run
tmpfs                4.0G     0  4.0G   0% /sys/fs/cgroup
/dev/mapper/ol-root   50G   18G   33G  36% /
/dev/sda1           1014M  224M  791M  23% /boot
/dev/mapper/ol-home   62G   33G   29G  53% /var/lib/docker
tmpfs                800M   12K  800M   1% /run/user/42
overlay               62G   33G   29G  53% /var/lib/docker/overlay2/46152c005aaf5cd34bedbc16f70287ed5143c26a4099f410c30a486c087c94e2/merged
tmpfs                800M     0  800M   0% /run/user/0

# blkid
/dev/sda1: UUID="477f8194-7c21-41d3-a38e-e56e321d0f54" TYPE="xfs"
/dev/sda2: UUID="pIIYNL-6ZL4-Uyho-IbvC-wnzu-v36n-fKcHqq" TYPE="LVM2_member"
/dev/sdb: TYPE="oracleasm"
/dev/sdc: TYPE="oracleasm"
/dev/mapper/ol-root: UUID="6f78ea28-e7f2-47f6-816e-1f598e350728" TYPE="xfs"
/dev/mapper/ol-swap: UUID="b272ffaf-3b67-4edc-8c6f-3ce59c9995bd" TYPE="swap"
/dev/mapper/ol-home: UUID="92c653de-7877-4000-94bc-08e9c698d269" TYPE="xfs"

# free -g
              total        used        free      shared  buff/cache   available
Mem:              7           2           1           1           3           4
Swap:             7           1           6
```

**Comment by psaini79** [comment] 2019-02-10 17:46
Hi, setup seems to be correct. However, memory seems to be low. Can we increase the memory? if yes, let me know I will give you db creation step to avoid all the work.

**Comment by scottwan** [comment] 2019-02-11 00:56
I increased the memory of docker host to 9G
```
[root@docker ~]# free -g
              total        used        free      shared  buff/cache   available
Mem:              8           0           8           0           0           8
Swap:             7           0           7
[root@docker ~]# free -m
              total        used        free      shared  buff/cache   available
Mem:           9000         317        8263          12         418        8525
Swap:          8063           0        8063
[root@docker ~]#
```

**Comment by scottwan** [comment] 2019-02-11 01:02
after the RAC container started:
```
[root@docker ~]# docker start racnode1
racnode1
[root@docker ~]# docker ps -a
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS               NAM                            ES
85d14841f764        oracle/database-rac:18.3.0   "/usr/sbin/oracleinit"   34 hours ago        Up 6 seconds                            rac                            node1
[root@docker ~]# docker exec -it racnode1 /bin/bash
[grid@racnode1 ~]$ free -g
              total        used        free      shared  buff/cache   available
Mem:              8           0           6           0           1           7
Swap:             7           0           7
[grid@racnode1 ~]$
[grid@racnode1 ~]$
[grid@racnode1 ~]$ free -m
              total        used        free      shared  buff/cache   available
Mem:           9000         885        6991          20        1123        7822
Swap:          8063           0        8063
```

**Comment by scottwan** [comment] 2019-02-11 01:17
the memory status after RAC container started 14 minutes:
```
[root@docker ~]# docker ps -a
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS               NAMES
85d14841f764        oracle/database-rac:18.3.0   "/usr/sbin/oracleinit"   34 hours ago        Up 14 minutes                           racnode1
[root@docker ~]#
[root@docker ~]# free -m
              total        used        free      shared  buff/cache   available
Mem:           9000        2517        2703        1940        3779        4238
Swap:          8063           0        8063

[root@docker ~]# docker exec -it racnode1 /bin/bash

[grid@racnode1 ~]$ free -m
              total        used        free      shared  buff/cache   available
Mem:           9000        2519        2700        1940        3779        4235
Swap:          8063           0        8063
```

**Comment by psaini79** [comment] 2019-02-11 23:58
This is expected as Oracle Grid need minimum 8GB of memory. Please see following documentation:

https://docs.oracle.com/en/database/oracle/oracle-database/18/cwlin/server-hardware-checklist-for-oracle-grid-infrastructure.html#GUID-D964EF96-9C9C-4173-A919-F3CAA72180B1

I will add extra checks for memory in RAC provisioning scripts inside the container. Also, I request if you can increase 2 to 3 GB to the container or your VM and try following:

Please execute following steps and let me know if you see any issue:

docker exec -i -t -u root racnode1 /bin/bash
cd /tmp
cp /opt/scripts/startup/dbca.rsp /tmp/dbca1.rsp
logdir=/tmp
DBCA_RSP="dbca1.rsp"
ORACLE_SID=PRODDB
ORACLE_PDB=PRODPDB
ORACLE_PWD=Oracle_12c
ORACLE_CHARACTERSET=AL32UTF8
PUBLIC_HOSTNAME=racnode1
CONTAINER_DB_FLAG=true

sed -i -e "s|###ORACLE_SID###|$ORACLE_SID|g" $logdir/$DBCA_RSP
sed -i -e "s|###ORACLE_PDB###|$ORACLE_PDB|g" $logdir/$DBCA_RSP
sed -i -e "s|###ORACLE_PWD###|$ORACLE_PWD|g" $logdir/$DBCA_RSP
sed -i -e "s|###ORACLE_CHARACTERSET###|$ORACLE_CHARACTERSET|g" $logdir/$DBCA_RSP
sed -i -e "s|###PUBLIC_HOSTNAME###|$PUBLIC_HOSTNAME|g" $logdir/$DBCA_RSP
sed -i -e "s|###DB_BASE###|$DB_BASE|g" $logdir/$DBCA_RSP
sed -i -e "s|###DB_HOME###|$DB_HOME|g" $logdir/$DBCA_RSP
sed -i -e "s|###CONTAINER_DB_FLAG###|$CONTAINER_DB_FLAG|g" $logdir/$DBCA_RSP

su - oracle
$DB_HOME/bin/dbca -silent -ignorePreReqs -createDatabase -responseFile /tmp/dbca1.rsp

Let me know the status.

**Comment by scottwan** [comment] 2019-02-12 02:06
```
# su - oracle
Last login: Mon Feb 11 11:32:55 UTC 2019 on pts/1
[oracle@racnode1 ~]$ $DB_HOME/bin/dbca -silent -ignorePreReqs -createDatabase -responseFile /tmp/dbca1.rsp
Prepare for db operation
7% complete
Copying database files
8% complete
[WARNING] ORA-00445: background process "DBW0" did not start after 120 seconds

[FATAL] ORA-01034: ORACLE not available

27% complete
100% complete
[FATAL] ORA-01034: ORACLE not available

7% complete
0% complete
Look at the log file "/u01/app/oracle/cfgtoollogs/dbca/PRODDB/PRODDB.log" for further details.
```

**Comment by scottwan** [comment] 2019-02-12 02:12
[PRODDB.log](https://github.com/oracle/docker-images/files/2853805/PRODDB.log)

**Comment by scottwan** [comment] 2019-02-12 02:26
```
$ free -m
              total        used        free      shared  buff/cache   available
Mem:          10230        2448        4122        1940        3658        5527
Swap:          8063           0        8063
```

**Comment by psaini79** [comment] 2019-02-12 03:42
Ok. Please provide the details of your shared storage? Are you using block devices?  Also, how did you configure your shared storage?

**Comment by scottwan** [comment] 2019-02-12 04:30
I think I am using the block devices

**Comment by scottwan** [comment] 2019-02-12 04:32
```
[root@docker ~]# fdisk -l

Disk /dev/sda: 129.0 GB, 128958595072 bytes, 251872256 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk label type: dos
Disk identifier: 0x0006298c

   Device Boot      Start         End      Blocks   Id  System
/dev/sda1   *        2048     2099199     1048576   83  Linux
/dev/sda2         2099200   251871231   124886016   8e  Linux LVM

Disk /dev/sdc: 19.3 GB, 19327352832 bytes, 37748736 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/sdb: 19.3 GB, 19327352832 bytes, 37748736 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/mapper/ol-root: 53.7 GB, 53687091200 bytes, 104857600 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/mapper/ol-swap: 8455 MB, 8455716864 bytes, 16515072 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes


Disk /dev/mapper/ol-home: 65.7 GB, 65733132288 bytes, 128385024 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
```

**Comment by scottwan** [comment] 2019-02-12 04:33
the script I used to create RAC container is:
```
docker create -t -i \
  --hostname racnode1 \
  --volume /boot:/boot:ro \
  --volume /dev/shm \
  --tmpfs /dev/shm:rw,exec,size=4G \
  --volume /opt/containers/rac_host_file:/etc/hosts  \
  --volume /opt/.secrets:/run/secrets \
  --dns-search=example.com \
  --device=/dev/sdb:/dev/asm_disk1  \
  --device=/dev/sdc:/dev/asm_disk2 \
  --privileged=false  \
  --cap-add=SYS_NICE \
  --cap-add=SYS_RESOURCE \
  --cap-add=NET_ADMIN \
  -e NODE_VIP=172.16.1.160 \
  -e VIP_HOSTNAME=racnode1-vip  \
  -e PRIV_IP=192.168.17.150 \
  -e PRIV_HOSTNAME=racnode1-priv \
  -e PUBLIC_IP=172.16.1.150 \
  -e PUBLIC_HOSTNAME=racnode1  \
  -e SCAN_NAME=racnode-scan \
  -e SCAN_IP=172.16.1.70  \
  -e OP_TYPE=INSTALL \
  -e DOMAIN=example.com \
  -e ASM_DEVICE_LIST=/dev/asm_disk1,/dev/asm_disk2 \
  -e ASM_DISCOVERY_DIR=/dev \
  -e CMAN_HOSTNAME=racnode-cman1 \
  -e CMAN_IP=172.16.1.15 \
  -e COMMON_OS_PWD_FILE=common_os_pwdfile.enc \
  -e PWD_KEY=pwd.key \
  --restart=always --tmpfs=/run -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
  --cpu-rt-runtime=95000 --ulimit rtprio=99  \
  --name racnode1 \
  oracle/database-rac:18.3.0
```

**Comment by scottwan** [comment] 2019-02-12 04:42
the only thing I did before creating the RAC container is:
```
dd if=/dev/zero of=/dev/sdb  bs=8k count=100000
dd if=/dev/zero of=/dev/sdc  bs=8k count=100000
```

**Comment by psaini79** [comment] 2019-02-12 05:31
This looks OK.  Please do following:
docker exec -i -t -u root  racnode1 /bin/bash
su - grid
export ORACLE_SID=+ASM1
asmcmd
lsdg
lsdsk

**Comment by psaini79** [comment] 2019-02-12 05:48
Also, can we try this on RAC storage server container i.e. with NFS just for testing. I wanted to make sure that there is not other env issue on your machine.  Do you have Oracle MOS access? Can you open a SR?

**Comment by scottwan** [comment] 2019-02-12 08:52
it seems it caused by the insufficient memory, I delete the RAC container, create and start the new one, it works.
```
02-12-2019 04:51:57 UTC :  : Checking Cluster Status
02-12-2019 04:51:57 UTC :  : Checking Cluster
02-12-2019 04:51:57 UTC :  : Cluster Check passed
02-12-2019 04:51:58 UTC :  : Cluster Check went fine
02-12-2019 04:52:00 UTC :  : MGMTDB Check went fine
02-12-2019 04:52:00 UTC :  : CRSD Check went fine
02-12-2019 04:52:00 UTC :  : CSSD Check went fine
02-12-2019 04:52:00 UTC :  : EVMD Check went fine
02-12-2019 04:52:00 UTC :  : Removing /tmp/cluvfy_check.txt as cluster check has passed
02-12-2019 04:52:00 UTC :  : Generating DB Responsefile Running DB creation
02-12-2019 04:52:01 UTC :  : Running DB creation
02-12-2019 06:17:06 UTC :  : Checking DB status
02-12-2019 06:17:28 UTC :  : #################################################################
02-12-2019 06:17:28 UTC :  :  Oracle Database ORCLCDB is up and running on racnode1
02-12-2019 06:17:28 UTC :  : #################################################################
02-12-2019 06:17:28 UTC :  : Running User Script
02-12-2019 06:17:28 UTC :  : Setting Remote Listener
02-12-2019 06:17:31 UTC :  : 172.16.1.15
02-12-2019 06:17:31 UTC :  : Executing script to set the remote listener
02-12-2019 06:17:39 UTC :  : ####################################
02-12-2019 06:17:39 UTC :  : ORACLE RAC DATABASE IS READY TO USE!
02-12-2019 06:17:39 UTC :  : ####################################

[root@docker ~]# free -g
              total        used        free      shared  buff/cache   available
Mem:              9           3           0           5           6           0
Swap:             7           0           7

[root@docker ~]# free -m
              total        used        free      shared  buff/cache   available
Mem:          10230        3371         257        5544        6601         981
Swap:          8063         545        7518
```

**Comment by scottwan** [comment] 2019-02-12 09:17
```
ASMCMD> lsdg
State    Type    Rebal  Sector  Logical_Sector  Block       AU  Total_MB  Free_MB  Req_mir_free_MB  Usable_file_MB  Offline_disks  Voting_files  Name
MOUNTED  EXTERN  N         512             512   4096  4194304     36864     8916                0            8916              0             Y  DATA/

ASMCMD> lsdsk
Path
/dev/asm_disk1
/dev/asm_disk2
```

**Comment by scottwan** [comment] 2019-02-12 09:52
I see service name 'ORCLCDB' from the listener status, but get error when connect this service name:
```
[oracle@racnode1 ~]$ lsnrctl status

LSNRCTL for Linux: Version 18.0.0.0.0 - Production on 12-FEB-2019 09:35:26

Copyright (c) 1991, 2018, Oracle.  All rights reserved.

Connecting to (ADDRESS=(PROTOCOL=tcp)(HOST=)(PORT=1521))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for Linux: Version 18.0.0.0.0 - Production
Start Date                12-FEB-2019 08:59:50
Uptime                    0 days 0 hr. 35 min. 36 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Listener Parameter File   /u01/app/18.3.0/grid/network/admin/listener.ora
Listener Log File         /u01/app/grid/diag/tnslsnr/racnode1/listener/alert/log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=LISTENER)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=172.16.1.160)(PORT=1521)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=172.16.1.150)(PORT=1521)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcps)(HOST=racnode1.example.com)(PORT=5500))(Security=(my_wallet_directory=/u01/app/oracle/product/18.3.0/dbhome_1/admin/ORCLCDB/xdb_wallet))(Presentation=HTTP)(Session=RAW))
Services Summary...
Service "+ASM" has 1 instance(s).
  Instance "+ASM1", status READY, has 1 handler(s) for this service...
Service "+ASM_DATA" has 1 instance(s).
  Instance "+ASM1", status READY, has 1 handler(s) for this service...
Service "81ad51c4b0f040a8e053960110ac3534" has 1 instance(s).
  Instance "ORCLCDB1", status READY, has 1 handler(s) for this service...
Service "ORCLCDB" has 1 instance(s).
  Instance "ORCLCDB1", status READY, has 1 handler(s) for this service...
Service "ORCLCDBXDB" has 1 instance(s).
  Instance "ORCLCDB1", status READY, has 1 handler(s) for this service...
Service "orclpdb" has 1 instance(s).
  Instance "ORCLCDB1", status READY, has 1 handler(s) for this service...
The command completed successfully

[oracle@racnode1 ~]$ sqlplus system@racnode-scan:1521/ORCLCDB

SQL*Plus: Release 18.0.0.0.0 - Production on Tue Feb 12 09:46:33 2019
Version 18.3.0.0.0

Copyright (c) 1982, 2018, Oracle.  All rights reserved.

ERROR:
ORA-12504: TNS:listener was not given the SERVICE_NAME in CONNECT_DATA


Enter user-name:
```

**Comment by psaini79** [comment] 2019-02-12 13:40
Glad it worked. I will enable more checks in container provisioning scripts.
I tried following on my machine and it worked:

[oracle@racnode1 admin]$ sqlplus system@\"racnode-scan:1521/ORCLCDB\"

SQL*Plus: Release 18.0.0.0.0 - Production on Tue Feb 12 13:39:14 2019
Version 18.3.0.0.0

Copyright (c) 1982, 2018, Oracle.  All rights reserved.

Enter password:
Last Successful login time: Tue Feb 12 2019 13:30:34 +00:00

Connected to:
Oracle Database 18c Enterprise Edition Release 18.0.0.0.0 - Production
Version 18.3.0.0.0

SQL>

**Comment by psaini79** [comment] 2019-02-12 13:41
sqlplus system@\"racnode-scan:1521/ORCLCDB\"

**Comment by psaini79** [comment] 2019-02-12 13:42
oh! it seems backslash are getting disappeared in markdown Editor. You need to put backslash '\' before double quotes.

**Comment by scottwan** [comment] 2019-02-12 14:53
I do not know why it does NOT work on my side.
```
[oracle@racnode1 ~]$ sqlplus system@racnode-scan:1521/ORCLCDB

SQL*Plus: Release 18.0.0.0.0 - Production on Tue Feb 12 10:22:35 2019
Version 18.3.0.0.0

Copyright (c) 1982, 2018, Oracle.  All rights reserved.

ERROR:
ORA-12504: TNS:listener was not given the SERVICE_NAME in CONNECT_DATA


Enter user-name: system
Enter password:
ERROR:
ORA-12162: TNS:net service name is incorrectly specified


Enter user-name: ^C
[oracle@racnode1 ~]$ sqlplus system@//"racnode-scan:1521/ORCLCDB"

SQL*Plus: Release 18.0.0.0.0 - Production on Tue Feb 12 10:23:21 2019
Version 18.3.0.0.0

Copyright (c) 1982, 2018, Oracle.  All rights reserved.


SQL*Plus: Release 18.0.0.0.0 - Production
Version 18.3.0.0.0

Copyright (c) 1982, 2018, Oracle.  All rights reserved.

Use SQL*Plus to execute SQL, PL/SQL and SQL*Plus statements.

**Usage 1: sqlplus -H | -V**
...
```

**Comment by scottwan** [comment] 2019-02-12 15:15
By the way, I have Oracle MOS access and I can you open a SR. so you can WebEx with me?

**Comment by scottwan** [comment] 2019-02-12 15:19
```
[oracle@racnode1 ~]$ tnsping ORCLCDB

TNS Ping Utility for Linux: Version 18.0.0.0.0 - Production on 12-FEB-2019 10:53:34

Copyright (c) 1997, 2018, Oracle.  All rights reserved.

Used parameter files:


Used TNSNAMES adapter to resolve the alias
Attempting to contact (DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = racnode-scan)(PORT = 1521)) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = ORCLCDB)))
OK (10 msec)

[oracle@racnode1 ~]$ tnsping racnode-scan:1521/ORCLCDB

TNS Ping Utility for Linux: Version 18.0.0.0.0 - Production on 12-FEB-2019 10:55:00

Copyright (c) 1997, 2018, Oracle.  All rights reserved.

Used parameter files:

Used HOSTNAME adapter to resolve the alias
Attempting to contact (DESCRIPTION=(CONNECT_DATA=(SERVICE_NAME=ORCLCDB))(ADDRESS=(PROTOCOL=TCP)(HOST=172.16.1.70)(PORT=1521)))
OK (0 msec)
```

**Comment by scottwan** [comment] 2019-02-12 15:28
```
[oracle@racnode1 ~]$ sqlplus system@ORCLCDB

SQL*Plus: Release 18.0.0.0.0 - Production on Tue Feb 12 11:01:32 2019
Version 18.3.0.0.0

Copyright (c) 1982, 2018, Oracle.  All rights reserved.

Enter password:
Last Successful login time: Tue Feb 12 2019 10:44:19 +00:00

Connected to:
Oracle Database 18c Enterprise Edition Release 18.0.0.0.0 - Production
Version 18.3.0.0.0

SQL> quit
Disconnected from Oracle Database 18c Enterprise Edition Release 18.0.0.0.0 - Production
Version 18.3.0.0.0


[oracle@racnode1 ~]$ sqlplus system@racnode-scan:1521/ORCLCDB

SQL*Plus: Release 18.0.0.0.0 - Production on Tue Feb 12 11:02:51 2019
Version 18.3.0.0.0

Copyright (c) 1982, 2018, Oracle.  All rights reserved.

ERROR:
ORA-12504: TNS:listener was not given the SERVICE_NAME in CONNECT_DATA

Enter user-name: ^C
```

**Comment by psaini79** [comment] 2019-02-12 15:41
Please use following format and it should work. Make you remove single quotes before running the command:

'sqlplus system@\"racnode-scan:1521/ORCLCDB\"'

Note: Please remove single quotes.

**Comment by psaini79** [comment] 2019-02-12 15:41
sqlplus system@\\"racnode-scan:1521/ORCLCDB\\"

**Comment by psaini79** [comment] 2019-02-12 15:45
Sure, open a SR and connect with me. I will be happy to assist you in further implementation. However, we will post all the issues with resolution in this thread so that it will be helpful to all the community users.

**Comment by scottwan** [comment] 2019-02-12 16:17
it seems connect to database using Easy Connect and the Service name was resolved as a Net Service Name.

**Comment by scottwan** [comment] 2019-02-12 16:22
```
[oracle@racnode1 ~]$ sqlplus system@"racnode-scan:1521/ORCLCDB"

SQL*Plus: Release 18.0.0.0.0 - Production on Tue Feb 12 11:55:55 2019
Version 18.3.0.0.0

Copyright (c) 1982, 2018, Oracle.  All rights reserved.

ERROR:
ORA-12504: TNS:listener was not given the SERVICE_NAME in CONNECT_DATA

Enter user-name: system
Enter password:
ERROR:
ORA-12162: TNS:net service name is incorrectly specified

Enter user-name: system
Enter password:
ERROR:
ORA-12162: TNS:net service name is incorrectly specified

SP2-0157: unable to CONNECT to ORACLE after 3 attempts, exiting SQL*Plus




[oracle@racnode1 ~]$ sqlplus system@\"racnode-scan:1521/ORCLCDB\"

SQL*Plus: Release 18.0.0.0.0 - Production on Tue Feb 12 11:57:28 2019
Version 18.3.0.0.0

Copyright (c) 1982, 2018, Oracle.  All rights reserved.

Enter password:
Last Successful login time: Tue Feb 12 2019 11:40:42 +00:00

Connected to:
Oracle Database 18c Enterprise Edition Release 18.0.0.0.0 - Production
Version 18.3.0.0.0

SQL> quit
Disconnected from Oracle Database 18c Enterprise Edition Release 18.0.0.0.0 - Production
Version 18.3.0.0.0
```

**Comment by scottwan** [comment] 2019-02-12 16:36
sorry, I am no longer approved to create SR. how do you know `sqlplus system@\"racnode-scan:1521/ORCLCDB\"` works?

**Comment by scottwan** [comment] 2019-02-12 17:14
thanks a lot, Easy Connect string works with backslash `\`.
I think this issue can be closed now.

**Comment by psaini2018** [comment] 2019-03-05 06:02
Please close this issue if you do not have any other query.

**Comment by psaini79** [comment] 2020-02-18 22:02
@anti996sz 

Closing this issue as  issue is resolved.

**Closed by psaini79** 2020-02-18 22:02 UTC
Labels: RAC
