### ISSUE TITLE
buildContainerImage.sh fails when called as documented in README.md

### ISSUE THREAD

**Issue by federico-razzoli** [oracle/docker-images#1944] opened 2021-05-24 18:11 UTC
```
federico@ip-192-168-0-24 dockerfiles % ./buildContainerImage.sh -i -e -v 19.3.0 -o '--build-arg SLIMMING=false'
Checking Docker version.
Ignored MD5 checksum.
==========================
Container runtime info:
Client:
 Debug Mode: false

Server:
 Containers: 21
  Running: 4
  Paused: 0
  Stopped: 17
 Images: 148
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.945GiB
 Name: docker-desktop
 ID: NXRS:72XU:GGFH:AJ6U:HOAD:Q6SF:S5VR:67RB:UHMZ:NKYP:GHCX:WJ2S
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

==========================
Building image 'oracle/database:19.3.0-ee' ...
[+] Building 1.5s (9/13)                                                                                      
 => [internal] load build definition from Dockerfile                                                     0.0s
 => => transferring dockerfile: 37B                                                                      0.0s
 => [internal] load .dockerignore                                                                        0.0s
 => => transferring context: 2B                                                                          0.0s
 => [internal] load metadata for docker.io/library/oraclelinux:7-slim                                    1.4s
 => CANCELED [base 1/4] FROM docker.io/library/oraclelinux:7-slim@sha256:6cb8ecfa0eee044040c73d9e92926b  0.0s
 => => resolve docker.io/library/oraclelinux:7-slim@sha256:6cb8ecfa0eee044040c73d9e92926b25de4f4b6a1ef4  0.0s
 => [internal] load build context                                                                        0.0s
 => => transferring context: 416B                                                                        0.0s
 => CACHED [base 2/4] COPY setupLinuxEnv.sh checkSpace.sh /opt/install/                                  0.0s
 => CACHED [base 3/4] COPY runOracle.sh startDB.sh createDB.sh dbca.rsp.tmpl setPassword.sh checkDBStat  0.0s
 => CACHED [base 4/4] RUN chmod ug+x /opt/install/*.sh &&     sync &&     /opt/install/checkSpace.sh &&  0.0s
 => ERROR [builder 1/2] COPY --chown=oracle:dba LINUX.X64_193000_db_home.zip db_inst.rsp installDBBinar  0.0s
------
 > [builder 1/2] COPY --chown=oracle:dba LINUX.X64_193000_db_home.zip db_inst.rsp installDBBinaries.sh /opt/install/:
------
failed to solve with frontend dockerfile.v0: failed to build LLB: failed to compute cache key: "/LINUX.X64_193000_db_home.zip" not found: not found

ERROR: Oracle Database container image was NOT successfully created.
ERROR: Check the output and correct any reported problems with the build operation.
```

My Docker version: 19.03.13

**Comment by gvenzl** [comment] 2021-05-24 18:14
Hi @federico-razzoli, you have to download/provide the installer file `LINUX.X64_193000_db_home.zip`:

```
failed to solve with frontend dockerfile.v0: failed to build LLB: failed to compute cache key: "/LINUX.X64_193000_db_home.zip" not found: not found
```

Another tip, if you run the `buildDockerImage.sh` without `-i` (ignore checksum), the script will make sure you have the right binary before attempting the build.

**Comment by huxaiphaer** [comment] 2022-01-19 07:41
I downloaded it and placed it in the `dockerfiles/<version>`, but I still get the same error, why is this ? @gvenzl

**Comment by huxaiphaer** [comment] 2022-01-19 08:34
I don't know if I misinterpreted this line :

> You will have to provide the installation binaries of Oracle Database (except for Oracle Database 18c XE and 21c XE) and put them into the dockerfiles/<version> folder

**Comment by alloro** [comment] 2022-02-22 09:33
@huxaiphaer the file needs to be in the dedicated version folder which you want to build. The Dockerfile references it by the copy statement. I left the file in the dockerfiles folder and created symlinks to each version I wanted to build.

**Comment by huxaiphaer** [comment] 2022-02-22 12:44
Thanks a bunch

**Comment by abhisbyk** [comment] 2022-05-30 08:57
It seems the issue is resolved. Closing this issue for now. Please reopen if it is still an issue.

**Closed by abhisbyk** 2022-05-30 08:57 UTC
Labels: database

**Comment by Bamal2024** [comment] 2024-09-19 22:07
i have the same problem, i dont understand how you solved it

**Comment by aDecoy** [comment] 2025-05-20 08:12
This is still a problem with 23.6.0
