### ISSUE TITLE
Error running Oracle Database 12.2.0.1 on larger server

### ISSUE THREAD

**Issue by gfelisberto** [oracle/docker-images#1714] opened 2020-09-15 15:27 UTC
I have been using `store/oracle/database-enterprise:12.2.0.1` as development database in a project. It is one of several containers running in a server (VM). The VM that we were using had 8 cores and 64GB of ram.

For some performance tests that we wanted to do we bumped the specs of the VM to 56 cores and 176GB of RAM. But when trying to run the system we noticed that we had errors starting the oracle container.  While trying to understand the problem we saw that the rrors even happened while running the simple docker `docker run -d -it --name teste store/oracle/database-enterprise:12.2.0.1`.

The oracle-clean.txt contains some info from the machine and the output of `docker logs`

[configDB.log](https://github.com/oracle/docker-images/files/5226040/configDB.log)

[oracle-clean.txt](https://github.com/oracle/docker-images/files/5226036/oracle-clean.txt)

**Comment by Djelibeybi** [comment] 2020-12-04 21:38
Closing because that image is no longer current. If you can reproduce this issue on the latest image released on Oracle Container Registry, please open an SR with Oracle Support.

**Closed by Djelibeybi** 2020-12-04 21:38 UTC
Labels: database
