### ISSUE TITLE
Oracle 18c xe Listener configuration failed on docker Windows

### ISSUE THREAD

**Issue by mmeseeburger** [oracle/docker-images#1125] opened 2019-01-23 14:46 UTC
I created an image from the Dockerfile for Oracle. I commented out the following line in the dockerfile, as I wanted to build an image without volume: #VOLUME ["$ORACLE_BASE/oradata"]

The builduing was successful. But I couldn't start a container with that image.
Getting out the following output after running "docker run --name oracle_build -p 1521:1521 oracle/database:18.4.0-xe":

ORACLE PASSWORD FOR SYS AND SYSTEM: 46b7f4b417cac95c
/etc/sysconfig/oracle-xe-18c.conf: line 3: $'\r': command not found
/etc/sysconfig/oracle-xe-18c.conf: line 6: $'\r': command not found
/etc/sysconfig/oracle-xe-18c.conf: line 9: $'\r': command not found
/etc/sysconfig/oracle-xe-18c.conf: line 12: $'\r': command not found
/etc/sysconfig/oracle-xe-18c.conf: line 16: $'\r': command not found
/bin/df: '\r': No such file or directory
Specify a password to be used for database accounts. Oracle recommends that the password entered should be at least 8 characters in length, contain at least 1 uppercase character, 1 lower case character and 1 digit [0-9]. Note that the same password will be used for SYS, SYSTEM and PDBADMIN accounts:
Confirm the password:
Configuring Oracle Listener.
Listener configuration failed. Check log '/opt/oracle/cfgtoollogs/netca/netca_configure_out.log' for more details.
mv: cannot stat '/opt/oracle/product/18c/dbhomeXE/dbs/spfileXE.ora': No such file or directory
mv: cannot stat '/opt/oracle/product/18c/dbhomeXE/dbs/orapwXE': No such file or directory
ORACLE_HOME = [/home/oracle] ? ORACLE_BASE environment variable is not being set since this
information is not available for the current user ID .
You can set ORACLE_BASE manually if it is required.
Resetting ORACLE_BASE to its previous value or ORACLE_HOME
The Oracle base remains unchanged with value /opt/oracle
bash: sqlplus: command not found
#####################################
########### E R R O R ###############
DATABASE SETUP WAS NOT SUCCESSFUL!
Please check output for further info!
#####################################
The following output is now a tail of the alert.log:
tail: cannot open '/opt/oracle/diag/rdbms/*/*/trace/alert*.log' for reading: No such file or directory
tail: no files remaining

Does anybody have an idea? Anyone with the same issue?

**Comment by IncredibleLou** [comment] 2019-01-24 07:12
I guess the problem is that the file `/etc/sysconfig/oracle-xe-18c.conf` has the wrong line delimiters (\r\n instead of just \n).

**Comment by IncredibleLou** [comment] 2019-01-24 20:56
#1128

**Comment by gvenzl** [comment] 2019-01-28 05:53
@mmeseeburger, @IncredibleLou, can you verify and confirm that this change solves the issue?

**Comment by IncredibleLou** [comment] 2019-01-28 12:49
I freshly cloned the repo with correct newline characters on my windows machine and the container can be started without any issues.

**Comment by gvenzl** [comment] 2019-01-28 15:24
Thanks for confirming!

I see @Djelibeybi has already merged the PR.

**Closed by gvenzl** 2019-01-28 15:24 UTC
Labels: database, more-info-required
