### ISSUE TITLE
Error in 19.03 docker image build

### ISSUE THREAD

**Issue by thinking-brain** [oracle/docker-images#2581] opened 2023-03-02 21:14 UTC
I'm trying to build the docker image for 19.03 and get this error:

> `Step 17/24 : COPY --chown=oracle:dba --from=builder $ORACLE_BASE $ORACLE_BASE
>  ---> e67194718fd8
> Step 18/24 : USER root
>  ---> Running in cb1718fc6771
> Removing intermediate container cb1718fc6771
>  ---> d1268d6bf8d1
> Step 19/24 : RUN $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh
>  ---> Running in 736543e58fd2
> /bin/sh: /opt/oracle/oraInventory/orainstRoot.sh: No such file or directory
> Removing intermediate container 736543e58fd2
> The command '/bin/sh -c $ORACLE_BASE/oraInventory/orainstRoot.sh &&     $ORACLE_HOME/root.sh' returned a non-zero code: 127
> 
> ERROR: Oracle Database container image was NOT successfully created.
> ERROR: Check the output and correct any reported problems with the build operation.`

I checked for that file in the zip file downloaded but it's missing.

Thanks

**Comment by CodesAreHonest** [comment] 2023-03-07 15:23
Face the same issue as mentioned by author.

**Comment by FlipperLP** [comment] 2023-04-03 14:17
Not the same error, but it's at the same line, that it was unable to find and run orainstRoot.sh

**Comment by aditya059** [comment] 2023-04-05 08:58
Hi @thinking-brain 
I tried the same on Ubuntu 22.04.2 LTS. I wasn't able to reproduce the issue. For me, the docker image built was successful. 

orainstRoot.sh is not supposed to be present in zip file. It is created during the build step. The error hints at an unsuccessful step earlier on. Please provide the entire output from the build script.

**Comment by aditya059** [comment] 2023-04-05 09:01
Hi @CodesAreHonest 
I tried the same on Ubuntu 22.04.2 LTS. I wasn't able to reproduce the issue. For me, the docker image built was successful. Please try as a non-root and provide the entire output from the build script (in case of error).

**Comment by aditya059** [comment] 2023-04-05 09:08
Hi @FlipperLP 
Please provide the entire output from the build script.

**Comment by FlipperLP** [comment] 2023-04-05 11:15
I don't have it anymore. It's just different because I run a newer version of Docker, but the underlying problem is the same.
The build process takes around 24 hours on my Rocky 9.1 VM as for some reason it only uses one core.
@aditya059 maybe try to build it with a clean docker build cache? Would it be possible to know which step generates the script(s)?

**Comment by thinking-brain** [comment] 2023-04-06 11:52
Hi @aditya059 
I use Manjaro and got that error. If you need more info to reproduce the error let me know.
Thanks

**Comment by aditya059** [comment] 2023-04-12 13:54
Hi @FlipperLP 
I am using Docker Version 23.0.3. I tried building with clean docker build cache. It was successful. I think that database installation step is failing on your machine because "orainstRoot.sh" is created during that step. Can you check whether there is enough space on your VM (~20gb)?

**Comment by aditya059** [comment] 2023-04-12 13:55
Hi @thinking-brain 
I think that database installation step is failing on your machine because "orainstRoot.sh" is created during that step. Can you check whether there is enough space (disk) on your machine (~20gb)?

**Comment by FlipperLP** [comment] 2023-04-12 14:04
> Hi @FlipperLP I am using Docker Version 23.0.3. I tried building with clean docker build cache. It was successful. I think that database installation step is failing on your machine because "orainstRoot.sh" is created during that step. Can you check whether there is enough disk space on your VM (~20gb)? Can you also provide the url from where you are downloading oracle database home zip file?

I had 20 GB of free space. I had probably more, but the VM doesn't exist anymore. The ZIP file seemed to be correct, as the md5 hash is checked.

**Comment by stecog** [comment] 2023-04-19 13:39
I cloned the repo now and went into `OracleDatabase/SingleInstance/dockerfiles`
```
./buildContainerImage.sh -v 19.3.0
Checking Docker version.
Checking if required packages are present and valid...
md5sum: Checksum.: No such file or directory
MD5 for required packages to build this image did not match!
Make sure to download missing files in folder 19.3.0.
```
???

**Comment by aditya059** [comment] 2023-04-19 13:47
@stecog Try with -i flag.

./buildContainerImage.sh -v 19.3.0 -i

**Comment by stecog** [comment] 2023-04-19 13:50
> @stecog Try with -i flag.
> 
> ./buildContainerImage.sh -v 19.3.0 -i

Sorry, I not have downloaded the zip files...

**Comment by aditya059** [comment] 2023-04-20 11:05
Hi,
Since this issue is not reproducible at our end (It may be disk space issue on your machine/vm), we are closing this. Please reopen with complete script output if the issue persists.

**Closed by aditya059** 2023-04-20 11:05 UTC
Labels: database
