### ISSUE TITLE
docker run for weblogic 12.2.1.2 image-dev cannot passing on domain name 

### ISSUE THREAD

**Issue by lisaxin** [oracle/docker-images#386] opened 2017-05-17 02:02 UTC
Hello, experts
I'm trying to using the weblogic 12.2.1.2 weblogic developer type image.
And would like th change the default domain name which is base_domain to others, but failed during parameter passing on during docker run.
Actually, no issue for the password passing on. 

```
>> Error: cd() failed. Do dumpStack() to see details.
>> Error: runCmd() failed. Do dumpStack() to see details.
>> Problem invoking WLST - Traceback (innermost last):
>>   File "/u01/oracle/create-wls-domain.py", line 61, in ?
>>   File "/tmp/WLSTOfflineIni6483412938482909160.py", line 55, in cd
>>   File "/tmp/WLSTOfflineIni6483412938482909160.py", line 19, in command
>>         at 
>> com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:69)
>>         at 
>> com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2768)
>>         at 
>> com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java:701)
>>         at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source)
>>         at 
>> sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>>         at java.lang.reflect.Method.invoke(Method.java:498)
>>
>> com.oracle.cie.domain.script.jython.WLSTException: 
>> com.oracle.cie.domain.script.jython.WLSTException: No match found for 
>> element SecurityConfiguration
```

Would you please give me any clue or hints?  Thanks in advance :)

Best Regards,
Lisa Xin

**Comment by lisaxin** [comment] 2017-05-22 07:49
Anybody has any hints? thanks

**Comment by kocic11** [comment] 2017-05-22 17:26
Lisa,

How do you build the image? Did you try building an image without changing the name? Was it successful?Also, can you post the output from the build process?

I can build the image using the following command (from OracleWebLogic/dockerfiles)

 sh buildDockerImage.sh -v 12.2.1.2 -d -s

Finally, it seems that you cannot change the domain name at the moment as it is defined as ENV variable.

Regards,
Aleksandar

**Comment by lisaxin** [comment] 2017-05-23 01:45
Hi, Aleksandar

Thanks a lot for your feedback.

I can build an image with no issue. It was successful just as you did.

sh buildDockerImage.sh -v 12.2.1.2 -d -s


However, we want to change the default domain name during the docker run of creating container. For example, instead of base_domain, we would like to use customized domain name such as abc. We cannot successfully made it. 

docker run -d -e DOMAIN_NAME=abc oracle/weblogic:12.2.1.2-developer

Not sure if there is any way to allow user to change the default domain name?


Regards,
Lisa

**Comment by kocic11** [comment] 2017-05-23 14:33
Lisa,

Can you try the following command:

docker run -d -e DOMAIN_NAME=abc -e DOMAIN_HOME=/u01/oracle/user_projects/domains/abc oracle/weblogic:12.2.1.2-developer

It works for me, although it is a workaround.

Regards,
Aleksandar

**Comment by mriccell** [comment] 2017-05-23 18:06
@lisaxin The domain nMe needs to be changed at image build time.  By the time the image has been created there is a WebLogic empty domain ( domain with a single admin server).  If you want to create a customized WLS domain extend the domain with a new Dockerfile that sets the domain name to what you want.  Look under samples 12212-domain.

**Comment by kocic11** [comment] 2017-05-24 21:01
Monica,

At the moment, it is not possible to change the domain name. DOMAIN_NAME is defined as the environment variable in oracle/weblogic:12.2.1.2-developer image and cannot be overwritten using build arguments ("Environment variables defined using the ENV instruction always override an ARG instruction of the same name."). This can be addressed by changing the DOMAIN_NAME from environment to argument variable.

In addition, from the practical point of view, I can see the advantage of having a single image, while setting the domain name during the run time instead of having many images with the only difference being the domain name. 

In general, would it be better to build a generic image and set the particular values during the run time, or should the images be as specific as possible?

Regards,
Aleksandar

**Comment by lisaxin** [comment] 2017-05-25 02:06
Aleksandar，

I have tried, the workaround works.
must add -e DOMAIN_HOME=/u01/oracle/user_projects/domains/abc  to make it works.

Regards,
Lisa

**Comment by lisaxin** [comment] 2017-05-25 06:19
Aleksandar，

I have tried, the workaround works.
must add -e DOMAIN_HOME=/u01/oracle/user_projects/domains/abc to make it 
works.

Thank you very much

Regards,
Lisa

**Comment by mriccell** [comment] 2017-06-01 23:39
I agree that setting the DOMAIN_NAME at run time is convenient specially when users have the same domain and all they need is to change the DOMAIN_NAME.  
What I do not understand is why if I set ENV DOMAIN_HOME=/u01/oracle/user_projects/domains/${DOMAIN_NAME:-base_domain} would it not automatically set the DOMAIN_HOME when the DOMAIN_NAME is set at runtime.
Monica

**Comment by kocic11** [comment] 2017-06-02 15:08
@mriccell It seems it is by design (tried a few options with the same result). Once the environment variable is set, it will not be substituted again, unless specifically set when running the container.

Considering this is not that important for an end user, the other option is to set it in one of the scripts or not set it at all and use the expanded version.

Regards,
Aleksandar

**Closed** 2017-06-08 15:21 UTC
Labels: help wanted, question, weblogic
